### ISSUE TITLE
multiple Select2

### ISSUE THREAD

**Issue by WaterSpout** [kartik-v/yii2-widgets#109]
Hello, when i try pass a value `multiple = true`

``` php
[
                'attribute'=>'last_profession',
                'value'=>'last_profession',
                'filterType'=>GridView::FILTER_SELECT2,
                'filter'=>ArrayHelper::map(Responses::find()->orderBy('last_profession')->asArray()->all(), 'last_profession', 'last_profession'),
                'filterWidgetOptions'=>[
                    'pluginOptions'=>['allowClear'=>true],
                    'options'=>['multiple'=>true],
                ],
                'filterInputOptions'=>['placeholder'=>'Любой']
            ],
```

And... filter dont work 
My actions:
1. Choose the first value
![first](http://cdn.joxi.ru/media/cache/thumbnail/uploads/prod/2014/07/14/74a/3ea/b246dc0f35763337558ea3fb64640cb14cb38e87.jpg)
its ok, next
2. Choose the second value
![second](http://cdn.joxi.ru/media/cache/thumbnail/uploads/prod/2014/07/14/7b8/902/9d55a5861b9a837745a34dea078957ce9190ff0b.jpg)
Page is automatically reloads and in the filter remains one thing the first value 
![seconds](http://cdn.joxi.ru/media/cache/thumbnail/uploads/prod/2014/07/14/948/486/7923cdb332660c6b31718cb88afcb4d9a623e8f5.jpg)
Multiple choose dont work.
And wrong duplicate get string `ResponsesSearch[last_profession]=&ResponsesSearch[last_profession][]=IT-директор`

Thanks =).

**Comment by ivan1911** [comment]
Hey WaterSpout, did you solve this issue ?

**Comment by cadr-sa** [comment]
any one found a solution?

**Comment by m-finger** [comment]
Same question!

**Comment by WaterSpout** [comment]
Yea, you can see here https://github.com/yiisoft/yii2/issues/4431
