### ISSUE TITLE
Multiple file upload

### ISSUE THREAD

**Issue by Kolyunya** [kartik-v/yii2-widgets#112]
Hello! I was not able to reproduce multiple file upload on your [demo-page](http://demos.krajee.com/widget-details/fileinput#). I was able to select only one file which was replaced by another one when I selected it. I will provide any additional information if you need it.

**Update**

Now I get it that you can only select multiple files together at once. Is it an expected behavior? I used to think that an expected behavior is to be able to add multiple files clicking `browse` one by one. Current behavior is unusable in my opinion because it's a quite common scenario when you need to attach files from distinct directories.

**Comment by isaiahgrant** [comment]
I recently wrote a fairly simple solution that may help others who come across similar issues. It can be found here: http://stackoverflow.com/questions/24889270/html-multiple-file-upload-from-different-folders. I am not sure if Github frowns upon referencing other sources, so just in case I copy/pasted the solution here as well!

How about this?

The solution uses HTML, jQuery/Javascript, and PHP (for server-side handling of this data). The idea is: 1.) HTML Form: Includes one "browse" button that allows the user to select multiple files (within one directory). 2.) jQuery: The option to create a new button in the form that allows users to select multiple files (within a different directory -- or even the same one actually!), with the ability to create new buttons "infinitely". 3.) PHP: As a bonus, I put some thought into packaging the data nicely for server-side handling.

Here is what the HTML form could look like (I used a found-icon for the clickable object, but you can easily replace it with a graphic of your choosing). 

    <form method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>" enctype='multipart/form-data'>
        Select files: <br/>
		<input type='file' name='files0[]' id="files0" multiple><br/><br/><br/>
		<span style="font-size: 10pt;">Click "+" for more files
        <i id="more_files" class="general foundicon-plus" style="color: blue;cursor: pointer;"></i></span>
		<br/><br/><br/>
		<input type="submit" name="submit" value="Submit">
    </form>

Here is the jQuery/Javascript to create a new "browse" button once the event is triggered (this even places it after the LAST "browse" button!):

    <script type="text/javascript">
	$(document).ready(function() {
		$(document).on('click','#more_files', function() {
			var numOfInputs = 1;
			while($('#files'+numOfInputs).length) { numOfInputs++; }//once this loop breaks, numOfInputs is greater than the # of browse buttons
			
			$("<input type='file' multiple/>")
				.attr("id", "files"+numOfInputs)
				.attr("name", "files"+numOfInputs+"[]")
				.insertAfter("#files"+(numOfInputs-1));
				
			$("<br/>").insertBefore("#files"+numOfInputs);
		});
	});
</script>

Finally, and possibly most important, how to wrap up the data on the server in a familiar format:

    <?php
	if(isset($_POST['submit']) && !empty($_FILES)) {
		$files = array();
		$files = $_FILES['files0'];
		//var_dump($files);//this array will match the structure of $_FILES['browser']
        //Iterate through each browser button
		$browserIterator = 1;
		while(isset($_FILES['files'.$browserIterator])) {
			//Files have same attribute structure, so grab each attribute and append data for each attribute from each file
			foreach($_FILES['files'.$browserIterator] as $attr => $values) {//get each attribute
				foreach($_FILES['files'.$browserIterator][$attr] as $fileValue) {//get each value from attribute
					$files[$attr][] = $fileValue;//append value
				}
			}
			$browserIterator++;
		}
		//Use $files like you would use $_FILES['browser'] -- It is as though all files came from one browser button!
		$fileIterator = 0;
		while($fileIterator < count($files['name'])) {
			echo $files['name'][$fileIterator]."<br/>";
			$fileIterator++;
		}
	}
    ?>
