### ISSUE TITLE
No results found and key separator in Select2 Tag

### ISSUE THREAD

**Issue by GuilhermeLessa** [kartik-v/yii2-widgets#126]
Hello, how could I clear the message "No results found" the formatNoMatches. In Select2 Tag.

And I would like to split the tag (closing tag) with [,] and [SPACE]. How?

Thanks!

**Comment by Dilden** [comment]
Came across this issue and just wanted to make a note that `formatNoMatches` has been changed to `noResults` and is located under `language`.

So the above code would now become

`'pluginOptions' => [
        'tags' => [],
        'multiple' => true,
        'initSelection' => new JsExpression($initScript),
        'language' => [
            'noResults' => null, //no message in search
        ],
        'tokenSeparators' => [',',' '], //space and comma are the separators
    ],`

[https://github.com/select2/select2/issues/4163#issuecomment-181611653](https://github.com/select2/select2/issues/4163#issuecomment-181611653)
