### ISSUE TITLE
Pjax gets aborted

### ISSUE THREAD

**Issue by iliyakolev** [kartik-v/yii2-widgets#134]
I'm using \yii\widgets\Pjax for the GridView. 
The ajax request gets aborted very often and a GET request is sent instead.
The bug is present even in the Kartik's demo: http://demos.krajee.com/grid-demo.
Thanks

**Comment by maulanayusuf** [comment]
I want to filter the kartik gridview on yii2, i have 2 combo box called AB and AC, each combo have filter variable the pjax filter work on first combobox, but when i try on the second combobox the url does not change.

on combobox i put this code on "onchange" event:
on combo 1 -> onclick="$.pjax.reload({url:'http://xyz.php?Model[fielda]=123',container: '#gridSoal',timeout: 1000,type:'GET'});"

on combo 2 -> onclick="$.pjax.reload({url:'http://xyz.php?Model[fieldb]=123',container: '#gridSoal',timeout: 1000,type:'GET'});"

please some one help me.
thanks.
