### ISSUE TITLE
Multiple file upload is not working after update

### ISSUE THREAD

**Issue by alexweb-zz** [kartik-v/yii2-widgets#142]
Looks like multiple file upload is not working after file-input (or yii2) update. 
It shows validation error message: You can upload at most 1 file.
Configuration is next:

``` php
echo $form->field($model, 'image[]')->widget(FileInput::classname(), [
    'pluginOptions' => [
        'showCaption' => false,
        'showRemove' => true,
        'showPreview' => false,
        'showUpload' => true,
        'browseLabel' => ' ',
        'removeLabel' => ' ',
        'elCaptionText' => '#caption-photo',
    ],
    'options' => [
        'accept' => 'image/*',
        'multiple'=>true,
    ]
]);
```

However it works when use this syntax:

``` php
echo FileInput::widget([
    'model' => $model,
    'attribute' => 'image[]',
    'pluginOptions' => [
        'showCaption' => false,
        'showRemove' => true,
        'showPreview' => false,
        'showUpload' => true,
        'browseLabel' => ' ',
        'removeLabel' => ' ',
        'elCaptionText' => '#caption-photo',
    ],
    'options' => [
        'accept' => 'image/*',
        'multiple'=>true,
    ]
]);
```

**Comment by nvshivakumar** [comment]
I implemented similar manner. But got below error
"The fileinfo PHP extension is not installed."
Is there any additional extension required. Note, I am using "fileInput" form element with multiple option

**Comment by mudris** [comment]
I have multiple upload error :

$model = new Media;
        if ($model->load(Yii::$app->request->post())) {
            // get the uploaded file instance. for multiple file uploads
            // the following data will return an array
            $image = UploadedFile::getInstance($model, 'photo');
 
            // store the source file name
error>>    $model->photo = $image->name;
            $ext = end((explode(".", $image->name)));
 
            // generate a unique file name
            $model->filename = Yii::$app->security->generateRandomString().".{$ext}";
 
            // the path to save file, you can set an uploadPath
            // in Yii::$app->params (as used in example below)
            $path = Yii::$app->params['uploadPath'] . $model->filename
