### ISSUE TITLE
Any plans for a tree view widget?

### ISSUE THREAD

**Issue by Jasrags** [kartik-v/yii2-widgets#143]
Perhaps based on fancytree or jstree?

**Comment by hashie5** [comment]
+1

**Comment by kartik-v** [comment]
New module [yii2-tree-manager](http://github.com/kartik-v/yii2-tree-manager) is created.

It is a complete tree management solution using nested sets and uses the yii2-nested-sets extension. It is built ground up and optimized for yii and does not use any third party plugins. Uses Krajee's own jquery plugins and bootstrap css.

Refer [documentation](http://demos.krajee.com/yii-kv/tree-manager) and demos for [TreeView](http://demos.krajee.com/yii-kv/tree-manager-demo/tree-view) and [TreeViewInput](http://demos.krajee.com/yii-kv/tree-manager-demo/tree-view-input)
