### ISSUE TITLE
Select2 in a renderPartial

### ISSUE THREAD

**Issue by nunomaduro** [kartik-v/yii2-widgets#155]
Hey,

After i saw this issue #73 i think that is not a good pratice load reload all asset's again, makes your website have a slow performance, especially if u have a HUGE appAsset's like me.

Is any way to trigger the render of select2 without reload all asset's again ?

**Comment by harryalwanga** [comment]
Hi I get this error Class 'kartik\widgets\Select2Asset' not found
What might be the problem?
