### ISSUE TITLE
Feature request for Select2: clear and select all buttons

### ISSUE THREAD

**Issue by RomeroMsk** [kartik-v/yii2-widgets#170]
Multiple Select2 is a good alternative for simple multiple `<select>` tag, but user can't select or clear all options with one or two simple key presses or clicks (like in `<select>` with Ctrl+A, Ctrl+click).
My request is to add 2 optional buttons (with `input-group-addon`):
1. Select all options
2. Clear selection (deselect all)

**Comment by macrawat** [comment]
Thanks kathik...!!
Select All is very much required in multiple select2.
But Clear Selection can be acheived by setting 'allowClear'  => true in pluginOptions.

**Comment by kartik-v** [comment]
Yes in the latest release v2.0.0 you now have the option to Clear ALL.

Select all is not included by default... its an enhancement needed.

**Comment by kartik-v** [comment]
This is resolved with kartik-v/yii2-widget-select2#69 and kartik-v/yii2-widget-select2#98.

**Comment by san05kits** [comment]
event not firing on select all in select2 
my sample code 

use kartik\select2\Select2;
use kartik\depdrop\DepDrop;


 <?= $form->field($model, 'iSample')->widget(DepDrop::classname(), [
                'data'      => ArrayHelper::map(Model::mufunction(), 'id', 'name'),
                 'type'      => DepDrop::TYPE_SELECT2,                  
                 'id'        => 'iSample',
                'options' => ['id'=>'iSample','multiple'=>true],
                'pluginOptions'=>[
                    'placeholder' => 'Select Sample...',
                    'allowClear' => true,
                    'params'     => ['iSample'], 
                    'depends' => ['doCommit'],
                    'url' =>  Url::to(['/controller/action']),
                ]
            ]); ?>
