### ISSUE TITLE
Select2 data property does not work as expected.

### ISSUE THREAD

**Issue by sanjarbek** [kartik-v/yii2-widgets#19]
```
echo $form->field($model, 'created_user')->widget(Select2::classname(), [
    'language' => 'ru',
    'size' => 'sm',
    'data' => array_merge(["" => ""], common\models\Ticket::getCreatedUsersList()),
    'options' => ['placeholder' => 'Выберите автора заявки ...'],
    'pluginOptions' => [
        'allowClear' => true
    ],
]);
```

static public function getCreatedUsersList()
    {
        $users = User::find()->where(['role' => User::ROLE_USER])->all();

```
    $usersArray = array();
    foreach ($users as $key => $user)
        $usersArray["$user->id"] = $user->showName();

    return $usersArray;
}
```

getCreatedUsersList is Ticket model's method. 
The result select is:
.....
<select id="ticketquery-created_user" name="TicketQuery[created_user]" placeholder="Выберите автора заявки ..." style="width: 100%" tabindex="-1" title="Создал" class="select2-offscreen">
<option value="" selected=""></option>
<option value="0">Тестов&nbsp;Тест</option>
</select>

As you see, option's value is not id of user.

**Comment by mfsi-deepakt** [comment]
When i create new data its working fine, but at the the of update, the select2:widget doesn't show any information or data . It goes blank. (Previous data cleared. How?)

**Comment by waml0478** [comment]
> When i create new data its working fine, but at the the of update, the select2:widget doesn't show any information or data . It goes blank. (Previous data cleared. How?)

I have the same problem... If i need to do an update in the data is it goes blank, i must add a new item and then when i save the data you can see the old and the new selection...

**Comment by nodirbeek** [comment]
> <?= $form->field($model, 'masullar')->widget(MultipleInput::className(), [
            'id' => 'my_id',
            'allowEmptyList' => false,
            'enableGuessTitle'  => true,
            'addButtonPosition' => MultipleInput::POS_FOOTER,
            'rowOptions' => [
                'id' => 'row{multiple_index_my_id}',
            ],
            'columns' => [
                [
                    'name'  => 'masul',
                    'type'  => \kartik\select2\Select2::className(),
                    // 'type'  => Select2::classname(),
                    'title' => 'Масъул',
                    'items' => $masullar,
                    'options' => [
                    'data' => $masullar,
                        'options'=>[
                             'onchange' => <<< JS
                        $.post("pochta?cb_id=" + $(this).val(), function(data){
                            $("#subcat-{multiple_index_my_id}").val(data.pochta);
                        });
                        JS,
                       'prompt' => '================'
                        ],
                  ],
                ],
                [
                    'name'  => 'pochta',
                    'type'  => 'textInput',
                    'title' => 'Почта',
                    'items' => '',
                    'options'=> [
                        'id' => 'subcat-{multiple_index_my_id}'
                    ],
                ],
            ]
    ])->label(false);
    ?>
