### ISSUE TITLE
kartik DepDrop not finding controller

### ISSUE THREAD

**Issue by arrigonfr** [kartik-v/yii2-widgets#190]
I'm trying to use the extension for a dependent dropdown, but it's still not working, I'll just post the code here and explain at the end of this thread.

My Tables

```
region_estados
   -id
   -descripcion

region_municipios
   -id
   -estados_id
   -descripcion
```

Parent DropDown

```
<?= 
Select2::widget([
                'model' => $model,
                'attribute' => 'estados_id',
                'data' => ArrayHelper::map(RegionEstados::find()->all(),'id','descripcion'),
                'options' => [
                            'placeholder' => 'Seleccione', 
                            'id'=>'regionparroquias-estados_id'
                            ],
                'pluginOptions' => ['allowClear' => true],
                ])
?>
```

Dependent DropDown

```
<?= 
$form->field($model, 'municipios_id')
     ->widget(DepDrop::classname(), [
                                    'type'=>DepDrop::TYPE_SELECT2,
                                    #'data'=>ArrayHelper::map(RegionMunicipios::find()->where(['estados_id' => $model->estados->id])->all(),'id','descripcion'),
                                    'options'=>[
                                        'id'=>'regionparroquias-municipios_id', 
                                        'placeholder'=>'Seleccione'
                                    ],
                                    'pluginOptions'=>[
                                        'depends'=>[Html::getInputId($model, 'estados_id')],
                                        'url'=>Url::to(['?r=region-estados/GetMunicipiosList']),
                                        'loadingText'=>'Cargando...',
                                        'initialize'=>($model->isNewRecord) ? false : true,
                                    ]
                ])
?>
```

My RegionEstados Controller

```
public function actionGetMunicipiosList() {
    $out = [];
    if (isset($_POST['depdrop_parents'])) {
        $parents = $_POST['depdrop_parents'];
        if ($parents != null) {
            $cat_id = $parents[0];
            $out = RegionMunicipios::getMunicipioList($cat_id);
            echo Json::encode(['output'=>$out, 'selected'=>'']);
            return;
        }
    }
    echo Json::encode(['output'=>'', 'selected'=>'']);
}
```

My RegionMunicipios model's function to retrieve the data (where I'm not exactly  sure how to return it

```
public function getMunicipioList($cat_id){
    $muni = RegionMunicipios::find()->where(['estados_id' => $cat_id])->asArray()->all();
    // First Way ->  $data = $muni; 
    $data = \yii\helpers\ArrayHelper::map($muni, 'id', 'descripcion'); // <- Second Way
    /*foreach ($muni as $i => $m) {
        $data[] = ['id' => $m['id'], 'name' => $m['descripcion']];
    }*/
    return $data;
}
```

Right now, this last function returns an array like this:

{
   "30":"ACHAGUAS",
   "31":"BIRUACA",
   "32":"MUNOZ",
   "33":"PAEZ",
   "34":"PEDRO CAMEJO",
   "35":"ROMULO GALLEGOS",
   "36":"SAN FERNANDO"
} 

Now, this is what happens when I select an option in the first dropdown:
    1. The second drop down show its loadingText.
    2. Nothing else. It just keeps loading.

I tried various combinations of ways of parsing the JSON array but nothing changes. I also tried (as you can see), different ways of writing the url parameter, and whether I put it between brackets, or not, or I use the Url class or not, changes nothing,the only thing that affects the behavior of the request, is whether or not I use the prefix '?r='.

When I don't use the prefix '?r=' this is what happens.

```
"NetworkError: 404 Not Found - http://localhost/yii2b/web/region-estados/GetMunicipiosList"
```

And when I do, it tries to find this url

```
http://localhost/yii2b/web/?r=region-estados/GetMunicipiosList  
```

When I DO use that prefix it tries to request the data and it doesn't show an error, the console acts as if everything was fine (even if i comment out or delete the function that i'm calling in the controller.

And if instead of using the prefix I instead try appending a '/' before the url (just like you would for the main), it tries to reach this url"http://localhost/region-estados/GetMunicipiosList", which of course doesn't exist.

Now, I don't even see why I should use the prefix '?r=' for the url, I'm only doing it because otherwise my console says it can't find the address, but I have enabled pretty urls in my components.

```
'urlManager' => [
            'class' => 'yii\web\UrlManager',

            // Disable index.php
            'showScriptName' => false,

            // Disable r= routes
            'enablePrettyUrl' => true,
    ],
```

Bottom line, if anyone can give me a hand here I'd appreciate it.

Just for some additional information: When using the url like this: 'url'=>Url::to('../?r=region-estados/GetMunicipiosList') this is what i see in the console.

```
Params

r region-estados/GetMunicipiosList

Header -Response Header

Cache-Control no-store, no-cache, must-revalidate, post-check=0, pre-check=0 Connection Keep-Alive Content-Length 4473 Content-Type text/html; charset=UTF-8 Date Fri, 31 Oct 2014 07:23:38 GMT Expires Thu, 19 Nov 1981 08:52:00 GMT Keep-Alive timeout=5, max=83 Pragma no-cache Server Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.5.15 X-Powered-By PHP/5.5.15

-Request Headers

Accept application/json, text/javascript, /; q=0.01 Accept-Encoding gzip, deflate Accept-Language en-US,en;q=0.5 Content-Length 24 Content-Type application/x-www-form-urlencoded; charset=UTF-8 Cookie __utma=111872281.817619947.1411963554.1414514577.1414516772.57; __utmz=111872281.1411963554.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _ga=GA1.1.817619947.1411963554; PHPSESSID=66gagsdrddkge36k6viqajv972; __utmc=111872281; _csrf=adeb24e2bcc08d45bfabd0da9fea7c0283b8e5f03b62558ce14fe06afebd98das%3A32%3A%22HbO8YcPR2Yr_quyzRxIA5Gt8i1Tl8A2i%22%3B User-Agent Mozilla/5.0 (Windows NT 6.2; WOW64; rv:32.0) Gecko/20100101 Firefox/ X-Requested-With XMLHttpRequest

Post Parameters depdrop_parents[0] 4 Source depdrop_parents%5B0%5D=4

Response returns the HTML script for /site/index for some reason
```

**Comment by themorfeo720** [comment]
hola que tal, tengo el mismo problema y no e logro solventar nada. arrigonfr  lograstes solventar el problema.?

**Comment by arrigonfr** [comment]
Si. Pues básicamente si tu función en el controlador se llama
actionDropdownCiudad y el controlador se llama CiudadesController.  En el
widget lo llamas con la url ciudades/dropdown-ciudad.  Ese era todo el
problema para mi. Más allá de eso tienes que ver que estés retornando los
resultados en el formato correcto. Eso lo puedes ver en stackoverflow.
Citaría alguno de mis ejemplos pero los he eliminado todos ya que he
decidido dejar de usar yii
