### ISSUE TITLE
FileInput can not upload file incorrectly ?

### ISSUE THREAD

**Issue by levanlau** [kartik-v/yii2-widgets#191]
Hi,
I have used InputFile widget,my current setting:
- ActiveForm : 'enctype'=>'multipart/form-data'
- ActiveField "file": 'multiple' => false
  My issue are: in view
- I have a code line such as  $form->field($model, 'file')->widget(FileInput::className(), [...
- If I only use a widget such as $form->field($model, 'name_field_any_1')->textInput([]), the uploading file up server is ok.
- But If I use more widget such as $form->field($model, 'name_field_any_2')->textInput([]), 
  $image=UploadedFile::getInstance($model, 'file') always return NULL value
- This mean is If I use > 1 ActiveField that format "textInput", I can not upload file up server.
  So, I can not understand this.
  Please give some suggestions.Thanks.

**Comment by mile-janev** [comment]
@levanlau Did you find solution for your problem? I have a similar one.
Thanks
