### ISSUE TITLE
Example missing for DisplayKey in typeahead widget

### ISSUE THREAD

**Issue by Alan01252** [kartik-v/yii2-widgets#215]
Hi,

Do you have an example of how to use this? I've tried but looking at the code I can't figure out how to get it to work. There's a very good chance I'm trying to make it do something it's not designed for, but essentially I have an array.

    [
    [id: 13123, title:"bla"]
    ]

And I'd like the code to use title but all I can ever make it get is [object Object]

What I'm doing atm.

     <?= $form->field($model, 'manufacturer_id')->widget(Typeahead::classname(), [
                'dataset' => [
                    [
                        'local' => Manufacturer::find()->where(['status' => '1'])->asArray()->all(),
                        'limit' => 10,
                        'displayKey' => 'title'
                    ]
                ],
                'pluginOptions' => ['highlight' => true],
                'options' => [
                    'placeholder' => 'Begin typing manufacturer name',
                ]
            ]);

Help would be greatly appreciated.

Cheers

Alan

**Comment by kartik-v** [comment]
The Typeahead plugin is not designed to achieve this - it uses the text field to search and return.

You can use the Select2 widget from yii2-widgets for your above use case (where you can store an id and show a different value). The widget also offers searching like the Typeahead.
