### ISSUE TITLE
disable asset auto registering

### ISSUE THREAD

**Issue by maxxi165** [kartik-v/yii2-widgets#218]
how to disable auto registering widget assets?
i set 
```
    'assetManager' => [
      'bundles' => [
          'kartik\select2\Select2Asset' => false,
      ],
    ],
```
but assets registering anyway

**Comment by kartik-v** [comment]
For most of my widget extensions it uses an enhanced AssetBundle in yii2-krajee-base. You need to disable JS & CSS this way:
```php
use \kartik\base\AssetBundle;
// ...
'assetManager' => [
    'bundles' => [
        'kartik\select2\Select2Asset' => [
            'js' => AssetBundle::EMPTY_ASSET,
            'css' => AssetBundle::EMPTY_ASSET,
        ],
    ],
],
```

However note that your core widget will be broken if the assets are not registered properly with the various validations as coded within the widget.

**Comment by maxxi165** [comment]
thanx!
