### ISSUE TITLE
Undefined variable: css

### ISSUE THREAD

**Issue by embambols** [kartik-v/yii2-widgets#220]
After updating everything with "composer update" command I get **Undefined variable: css** error in *...\vendor\kartik-v\yii2-widget-activeform\ActiveField.php* around line 391 when ever I use checkboxList() or radioList()
I guess the problem is a missing **$css** at the end of this line: 
```
$options['item'] = function ($index, $label, $name, $checked, $value) use ($type) {
```

**Comment by kartik-v** [comment]
you need to get the latest update of yii2-widget-activeform from dev-master where this is fixed along with other issues.  I will tag a new release soon when this should be autoupdated for stable releases.

**Comment by embambols** [comment]
ok, thanks. Not sure how to do that, but I'll look into it. btw your widgets are awesome! keep up the good work
