### ISSUE TITLE
Switchinput combined with tabs is not working

### ISSUE THREAD

**Issue by hashie5** [kartik-v/yii2-widgets#221]
I use a switchinput combined with tabs (and tabs-x) and get these bugs:  
- When the switchinput is not on the first tab, you can't set the default value to false  
- When I switch tabs (tabs-x) the switchinput changes back to a normal checkbox

**Comment by kartik-v** [comment]
Related to #12 and #13. Upgrade to latest release.

**Comment by hashie5** [comment]
thanks
