### ISSUE TITLE
Can't use dropdown on sidenav

### ISSUE THREAD

**Issue by ghost** [kartik-v/yii2-widgets#222]
![can dropdown](https://cloud.githubusercontent.com/assets/9666842/5885224/cd6e12c0-a3a3-11e4-9ccd-490c3e37be96.png)
![can t dropdown menu](https://cloud.githubusercontent.com/assets/9666842/5885225/cd7617cc-a3a3-11e4-878c-6ec43ae450d3.png)

in index I can use dropdown on sidenav, but when I go to About menu  I can't use dropdown sidenav..
can someone help me??

**Comment by kartik-v** [comment]
Cross check and see if you have not directly hyperlinked the about menu.
