### ISSUE TITLE
ERROR: uncaught exception: query function not defined for Select2 account-account_type_id

### ISSUE THREAD

**Issue by cloudcaptain** [kartik-v/yii2-widgets#224]
Following the example on: http://demos.krajee.com/detail-view-demo.

    [   'attribute'=>'account_type_id',
                    'format'=>'raw',
                    'value' => AccountType::getAccountTypeName($model->account_type_id),
                    'type'=>CustomDetailView::INPUT_SELECT2, 
                    'widgetOptions'=>[
                        'data'=> BaseArrayHelper::map($accountType->find()->select(['id','name'])->from('account_type')->orderBy('id')->asArray()->all(),'id','name');
                        'options'=>['placeholder' => ' '],
                        'pluginOptions'=>['allowClear'=>true]
                    ],
                    'inputWidth'=>'40%'
                ],

What am I doing wrong?

**Comment by kartik-v** [comment]
As mentioned in the message, you seem to be using an invalid query. You must use ModelClass::find() method instead of model instance... so
```php
AccountType::find()
```
instead of
```php
$accountType->find()
```

**Comment by cloudcaptain** [comment]
**The error is still there.**
*uncaught exception: query function not defined for Select2 account-account_type_id*
Here are the new attributes as instructed ...

                [   'attribute'=>'account_type_id',
                    'format'=>'raw',
                    'value' => AccountType::getAccountTypeName($model->account_type_id),
                    'type'=>CustomDetailView::INPUT_SELECT2, 
                    'widgetOptions'=>[
                        'data'=> AccountType::listAccountTypeIdNames(),
                        'options'=>['placeholder' => 'Select ...'],
                        'pluginOptions'=>['allowClear'=>true]
                        //'size'=>'SMALL',
                    ],
                    'inputWidth'=>'40%'
                ],

*Here's the function:*
      public static function listAccountTypeIdNames()
      {
          $accountType = new AccountType();;
          return \yii\helpers\BaseArrayHelper::map(
                      $accountType->find()
                          ->select(['id','name'])
                          ->from('account_type')
                          ->orderBy('id')
                          ->asArray()->all(),
                  'id','name');
      }

*Here's the output from the function:*
      Array ( [1] => Income [2] => Expense [3] => Asset [4] => Liability )

**Comment by cloudcaptain** [comment]
**Found the problem.**

Error was caused because there were two fields listed in the attributes called account_type_id.  Removed the other field, which was there for testing verification.  The code works just fine now.
