### ISSUE TITLE
Asset class registration

### ISSUE THREAD

**Issue by jekamoroz** [kartik-v/yii2-widgets#226]
How about to add possibility use this widget without twitter bootstrap css. Because it is useful in admin panel for example, but it is useless for client part when the last don't built with tw bootstrap css.

I also tried to overload for example select2 and it's asset, but it select2 initiates inside registerAsset function which holds many other specific to kartik's widget logic.

So, my purpose to separate somehow the the asset registration to make overloadable

Thank you

**Comment by kartik-v** [comment]
Most of the extensions I built have a bootstrap dependency and have been constructed for bootstrap styling. 

You would need to override and recreate the CSS for your own use-case if you do not need Bootstrap.
