### ISSUE TITLE
Select 2 text not displaying in update view

### ISSUE THREAD

**Issue by RoyAMR** [kartik-v/yii2-widgets#227]
Hi, I'm using select2 to fill a value in my form, the problem i have is that in the update view the value is set but it doesn't display the text, is it possible to do so? Here's my code:
$initScript = <<< SCRIPT
	function (element, callback) {
    	var id=\$(element).val();
    	if (id !== "") {
        	\$.ajax("{$url}?id=" + id, {
            dataType: "json"
        }).done(function(data) { callback(data.results);});
    }
}
SCRIPT;
 
// The widget
echo $form->field($model, 'socio_uuid')->widget(Select2::classname(), [
    'options' => ['placeholder' => 'Nombre'],
    'pluginOptions' => [
        'allowClear' => true,
        'ajax' => [
            'url' => $url,
            'dataType' => 'json',
            'data' => new JsExpression('function(term,page) { return {search:term}; }'),
            'results' => new JsExpression('function(data,page) { return {results:data.results}; }'),
        ],
        'initSelection' => new JsExpression($initScript)
    ],
]); ?>

**Comment by claudiogg88** [comment]
i have the same problem, but without ajax,

```
  'IdCondicionIVA' => [ 'type' => Form::INPUT_WIDGET,
                'widgetClass' => \kartik\widgets\Select2::classname(),
                'options' => [
                    'language' => 'es',
                    'options' => ['placeholder' => 'Seleccione Condicion IVA...'],
                    'pluginOptions' => [
                        'allowClear' => true,  
                        'templateResult' => new \yii\web\JsExpression('formatearResultadoCondicionIVA'),
                        'templateSelection' => new \yii\web\JsExpression('formatearSeleccionCondicionIVA'),
                        'data' => app\models\CondicionIVA::Resumir()
                    ],
                ],
            ],

  public static function Resumir()
    {
        $lista = CondicionIVA::find()->orderBy('IdCondicionIVA')->all();
        $props = [
            'app\models\CondicionIVA' => [
                'id' => function ($obj) {
                    return $obj->IdCondicionIVA;
                },
                'text' => function ($obj) {
                    return $obj->Descripcion;
                },
                'IdCondicionIVA',
                'Codigo',
                'Descripcion',
                'Alicuota'
            ],
        ];
        $resumido = \yii\helpers\ArrayHelper::toArray($lista, $props);
        return $resumido;
    }

```
the field select the id but not show the text, it's a bug from select2?? thanks
