### ISSUE TITLE
Select2 Ids with CSS Special Characters

### ISSUE THREAD

**Issue by EAnushan** [kartik-v/yii2-widgets#228]
I'm using a Select2 filter column in a GridView as shown below:
```
<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'name',
            'description',
            'picture',
            [
				'attribute'=> 'inventoryCategory.name',
				'format' => 'raw',
				'filter' => Select2::widget([
					'model' => $searchModel,
					'attribute' => 'inventoryCategory.name',
				    'data' => ArrayHelper::map(InventoryCategory::find()->all(), 'name', 'name'),
				    'options' => ['placeholder' => 'Select ' . $searchModel->getAttributeLabel('inventory_category_id') . '...'],
				    'pluginOptions' => ['allowClear' => TRUE],
    			]),
				'value'=> function($model, $key, $index, $column)
				{
					return Html::a(Html::encode($model->inventoryCategory->name), ['inventory-category/view', 'id' => $model->inventoryCategory->id]);
				}
			],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
```

The problem is, the "id" attribute for the select that is generated is named "inventorysearch-inventorycategory.name". Since the period in the id is used for css class selection, the "initSelect2Loading()" JavaSscript method in select2-kv.js fails to remove the loading classes from the select. In fact, most of the JavaScript fails silently because the selector can't find the element.

Fix is relatively simple, in Select2.php, registerAssets() method, instead of using $id for the jQuery selector, first escape all CSS special characters.

```
$jqueryId = str_replace('.', '\\\.', $id);
```

The above only replaces periods, but there are other special characters, like [ or ].

**Comment by kartik-v** [comment]
Just provide your own unique id in the `options` property for the Select2 widget.

No need of any other complicated changes.
