### ISSUE TITLE
Not work with pjax

### ISSUE THREAD

**Issue by Assada** [kartik-v/yii2-widgets#229]
![Image of Yaktocat](http://i.imgur.com/Sb8PlsB.gif)

Widgets not work with pjax load. With simple reload - all ok.

**Comment by kartik-v** [comment]
Need to be specific in your query which widget - as there are many widgets in this bundle?

From the screenshot it seems you are using the FileInput widget. If you are rendering any jquery plugins via Pjax... you would need to reinitialze the plugin - else they will not work . You can reinitialize the plugin on `pjax:complete` or `pjax:reload` events with a code like below:

```js
var $id = $("#input-id"); // your file input id
$id.fileinput($id.data(krajeeFileinput'));
```

**Comment by Assada** [comment]
fileinput is not a function.
Because on other page libs not included. How i can force include wigets(partical) lib(css, js) on all pages (such as BootstrapAsset)?

**Comment by kartik-v** [comment]
You can try Yii's `renderAjax` method in controller to render the content via pjax.

**Comment by dubeymahi48** [comment]
Hii kartik,

Js file is not included when we are loading page with renderAjax method using pjax. this problem is with all widgets.

**Comment by kartik-v** [comment]
I am not clear what's your query or what's the expectation.

Yes the JS file will not be included via `renderAjax` if it already is loaded on the page (which will be the use case). The `renderAjax` method should typically reload JS or CSS scripts (and not JS/CSS files) again (basically scripts that have been registered via `registerJs` or `registerCss`). 

This is what is expected to happen with `renderAjax`.

**Comment by kartik-v** [comment]
I can understand now from the screenshot - what you want to do... you basically do not have the widget loaded in the first place.

What I suggest for your use case is:
- create a custom view layout by removing all header/footer or already loaded asset bundles etc.
- then to use yii's `render` method directly using the above layout to render the view

**Comment by kartik-v** [comment]
@Assada I can understand now from the screenshot - what you want to do... you basically do not have the widget loaded in the first place and hence the widget assets / files are not loaded on the page.

What I suggest for your use case is:
- create a custom view layout by removing all header/footer or already loaded asset bundles etc.
- then use yii's `render` method directly using the above layout to render the view  (not renderAjax or renderPartial).
