### ISSUE TITLE
DateTimePicker has a cross button and DatePicker doesn't

### ISSUE THREAD

**Issue by germansokolov13** [kartik-v/yii2-widgets#231]
I was looking for an option to add a clear button with a cross to the DatePicker but found none. Why do those widgets have this different interface? I worry it might confuse users as they will look for a cross and won't find it. Is there a reason to it or a way to fix it?

Great thanks for your help.

**Comment by kartik-v** [comment]
These widgets are based on two different plugins by two different authors (and I am not an author of the two plugins). The clear button is a functionality offered by bootstrap-datetimepicker plugin only.

I have tried best though to maintain the bootstrap styling consistency between the two widgets with some additional enhancements as options to the widget.

Ideal thing will be to request a feature enhancement in the bootstrap-datepicker plugin repo.

I  may figure later if I could enhance this through the widget - if that's not done in the source plugin.

**Comment by kartik-v** [comment]
New enhancements have been added separately to <b>yii2-widget-datepicker</b> to configure `pickerButton` and `removeButton` similar to <b>yii2-widget-datetimepicker</b>.

Refer [documentation](http://demos.krajee.com/widget-details/datepicker) and [usage demos](http://demos.krajee.com/widget-details/datepicker#usage).
