### ISSUE TITLE
Js file is not included with renderAjax...

### ISSUE THREAD

**Issue by dubeymahi48** [kartik-v/yii2-widgets#232]
Hii kartik,

Js file is not included when we are loading page with renderAjax method using pjax. this problem is with all widgets.

**Comment by kartik-v** [comment]
Duplicate [to this](https://github.com/kartik-v/yii2-widgets/issues/229#issuecomment-76936991).

**Comment by dubeymahi48** [comment]
Thank you for a perfect reply...
Work perfectly now....
