### ISSUE TITLE
Hello typeahead i need save pers_auxi but when i save this is 0 every time :S help  me pls 

### ISSUE THREAD

**Issue by cronos24** [kartik-v/yii2-widgets#234]
<?php 

    $data = GeTpers::find()
    ->asArray()
    ->all();

    $niceData = yii\helpers\ArrayHelper::map($data, 'pers_auxi', 
    function($element){
      return $element['pers_nom1'] ." ".  $element['pers_nom2'] ." ". $element['pers_ape1'] ." ". $element['pers_ape2'] ."  ". $element['pers_ndoc'] ;
    });
/* print_r($niceData); => Array ( [1] => ERICK DAYAN MARTINEZz GOMEZ 1098694780 [2] => LAURA PATRICIA CONTRERAS GARCIA 1098694752 )*/
     ?>

    <?php 

    echo $form->field($model, 'pers_auxi')->widget(Typeahead::classname(), [
    'dataset' => [
        [
            'local' => $niceData,
            'limit' => 10
        ]
    ],
    'pluginOptions' => ['highlight' => true],
    'options' => ['placeholder' => 'Seleccione un Tercero...'],
]);
    ?>

**Comment by kartik-v** [comment]
Cannot understand the issue. Cross check your data source and your widget configuration (check the demo pages if needed).

You may [post and request for general programming help and tips in this new Q & A forum](http://webtips.krajee.com/questions).
