### ISSUE TITLE
preselcted with your example not work 

### ISSUE THREAD

**Issue by kiamoz** [kartik-v/yii2-widgets#235]
Dear @kartik-v  ,
here is my code with your guide : 

$data = [1=>'category 1', 2=>'category 2', 3=>'category 3'];
$model->parent_id = 2;    
echo Select2::widget([
   'model'=>$model,
   'attribute' => 'parent_id',
   'data' => $data
]);

but not selected yet!
what's wrong with my code ?
thanks in advance .

kiarash

**Comment by kartik-v** [comment]
Yes I checked your code is fine and should show `category 2` as selected by default.

You may need to debug your env and see if you have any other errors on your page.
