### ISSUE TITLE
Combining and compressing asset bundles

### ISSUE THREAD

**Issue by manquer** [kartik-v/yii2-widgets#236]
All Assets for the widgets use `kartik\widgets\AssetBundle::setupAssets()` function within the init() call to setup assets, instead of declaring object property directly, like this

````
 public function init()
    {
        $this->setSourcePath(__DIR__ . '/../lib/select2');
        $this->setupAssets('css', ['select2', 'select2-bootstrap3']);
        $this->setupAssets('js', ['select2']);
        parent::init();
    }
````
For creating compressed combined using `yii\console\Controllers\ImportController::actionCompress`  builds targetBundles using `Yii::createObject()` method. However createObject does not make the init call, therefore while compressing, these assets are not being included and they are getting separately registered.  There are lot of wrapper classes in this and your other repositories , ability to compress into single js and css assets is important in production.

The `setupAssets()` call can either move to `__contruct()` or better the assets attributes be declared as properties directly to allow compression to happen.

**Comment by kartik-v** [comment]
Not sure if you have something custom for your app

1. I am not aware of any `yii\console\Controllers\ImportController` and its impact
2. If you are talking about combining and compressing asset bundles - you need to follow this [yii guide for combining and compressing assets](http://www.yiiframework.com/doc-2.0/guide-structure-assets.html#combining-and-compressing-assets).

Yes there is a special setup for `setupAssets` but if you use the method mentioned as highlighted in point 2 - you should not face issues.

**Comment by manquer** [comment]
1.  my mistake  I meant  yii\console\Controllers\AssetController::actionCompress() . it was typo.

2. I am following the same and all other assets are getting registered fine. only assets in from this widgets are not getting generated.
The AssetBundles are included in the generated bundles file, however generated css and js files does not include the files from the bundles. This is because the cs and js attributes are only set during init().

 If I override the setupAsset() function and setup the properties manually and after that regenerate the compressed files, everything works and all the files are correctly compressed. 
From what i understood actionCompress() calls loadTarget() in [AssetController#177](https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/AssetController.php#177) which in turn calls createObject to generate AssetBundle objects in [AssetController#313]
(https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/AssetController.php#L313) 
I believe the init() call is not made if object is generated using createObject, I am not very familiar with DI and Service Locators so I am not sure how it works beyond that. 

Sorry if I am not very clear or if my explanation is confusing, If you test compressing with your widgets Assets registered perhaps it will be clearer to you

**Comment by kartik-v** [comment]
The init method is called... and assets are combined in my tests.

**Comment by kartik-v** [comment]
The init method is called... and assets are combined in my tests.

Note that yii calls the init method for all Yii objects in its `__construct` - [have a look here](https://github.com/yiisoft/yii2/blob/master/framework/base/Object.php#L107)

**Comment by manquer** [comment]
Thanks I understand how Yii Objects work better now.. you are correct I var_dumped the inputFiles  before compression from the core buildTarget call [here](https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/AssetController.php#L348) and  the js and css are included in the compressed output.

However the issue is the same the js and css are again called in the specific form pages where the widget is used. Now I have no idea what is reason behind this behavior, the network trace below kind of illustrates whats happening 

![image](https://cloud.githubusercontent.com/assets/3044333/6656917/c12c3940-cb5f-11e4-811f-86c7027cf433.png)

Sorry if the screenshot is not helping, I can share the asset config file and widget form call in gist if you wish to see the same

**Comment by kartik-v** [comment]
All I can say is, you need to set the asset manager component correctly in your yii configuration [as described in the combining and compressing assets section of the yii guide](http://www.yiiframework.com/doc-2.0/guide-structure-assets.html#combining-and-compressing-assets).

Each asset bundle like `kartik\widgets\Select2` needs to have the right entry in asset manager. Anyway its something for you to debug and find out.

**Comment by manquer** [comment]
Sure.. i understand,  I think I figured out what is the problem.. on generating the bundles the generated files sets js and css properties to null like this in the application config
````
 'kartik\\widgets\\Select2Asset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'allApp',
        ],
    ],
```
When you are making the setupAsset call you are setting up the js and css properties if they are null with this. 
````
if (empty($this->$type)) {
            $this->$type = YII_DEBUG ? $srcFiles : $minFiles;
 }
````
Because the values are set again the assets are published again. 

I checked the assetBundle values for other bundles they remain null when registered, however for the widgets from this extension the values are being set, therefore the problem. 

If you think that this behavior is due to config on my side let me know I will fork and do a dirty hack by commenting out the setting up attributes part for now ( this will break in the non combined case so not a real solution), however if you think the issue is real on the widget side, then I will wait for your update :)..
 thank you for responses

**Comment by kartik-v** [comment]
You sure seem to have an outdated or very old version of `kartik\base\AssetBundle`.

Cross check the kartik-v/yii2-krajee-base repo and ensure you have the updated files.

The `kartik\base\AssetBundle` has been coded very intelligently to work with yii's asset manager as well as to allow people to selectively use minified files where they do not wish to combine assets.

Note that the latest version of `kartik\base\AssetBundle has a `setupAssets` method which does not have the validation you mention. [Refer it here](https://github.com/kartik-v/yii2-krajee-base/blob/master/AssetBundle.php#L56)

**Comment by manquer** [comment]
Ah, thank you , 
I am currently on "kartik-v/yii2-widgets": "2.*@stable", I will update to latest which i see 3.4.x (hopefully update won't break anything)
for clarity that is not the AssetBundle class being actually called ( the class called is within kartik\widgets namespace in 2..x) , i guess you re-factored the bundle into the base repo during 3.x(?) update, 
to add to my confusion the latest version of kartik\base\AssetBundle is also preent due to other dependencies i was checking that at first, then found the call was from same namespace.

Out of curiosity, was this due to design change in core asset manager or a bug in 2.x in widget ? What I mean is that could this have been avoided by limiting composer to that particular commit/version tag forcing an update or unresolved dependency
However if it was bug fixed in only later branches nothing could have been done, supporting multiple versions is of course not realistic in project of this nature .

Anyway thank you helping out.. I will close this

**Comment by thrieu** [comment]
I followed the last 2 paragraphs of http://www.yiiframework.com/doc-2.0/guide-structure-assets.html, but I got such like this:

>  Uncaught TypeError: $(...).resizableColumns is not a function

It seems I encounter the same problem. Could @manquer tell me is there any follow-up on this issue?
