### ISSUE TITLE
kartik\widgets\DatePicker

### ISSUE THREAD

**Issue by rachmankidal** [kartik-v/yii2-widgets#238]
Dear all,
I am still new with YII, 
when I try create code with YII and Kartik, found Error :  
" Fatal error: Class 'kartik\yii2daterange\DateRangePicker' not found in C:\xampp\htdocs\latihan4\protected\views\layouts\main.php "

<?php
		
		use kartik\widgets\DatePicker;
		use kartik\yii2daterange\DateRangePicker;
		
	    echo DateRangePicker::widget([
			'model'=>$model,
			'attribute'=>'datetime_range',
			'convertFormat'=>true,
			'pluginOptions'=>[
				'timePicker'=>true,
				'timePickerIncrement'=>30,
				'format'=>'Y-m-d h:i A'
			]
		]);

    ?>

What problem & what must I do 
Thank for your help

Rachman

**Comment by kartik-v** [comment]
Use this project page ONLY for logging issues / bugs / enhancement suggestions for the widget

For newbie help or your personal app queries use the [widget comments page](http://demos.krajee.com/date-range) or the yii forums. BTW your query is answered in the [yii forum](http://www.yiiframework.com/forum/index.php/topic/62742-use-yii-and-kartik-widget/page__view__findpost__p__277288).
