### ISSUE TITLE
pjax option in GridView widget

### ISSUE THREAD

**Issue by nbk-kolyan** [kartik-v/yii2-widgets#240]
I have the ajax problem with youre gridView widget Kartik.
The problem is with youre pjax => true.
I have the field = standart Datepicker widget.
after filter form, using pjax, this widget stops works.
I fix this by putting

 Pjax::begin() .. GridView .. Pjax::end

Now default Datepicker works. I thought that i need to re register js scripts, but replacing youre pjax option with default Pjax widget fixed the problem

**Comment by kartik-v** [comment]
pls post in correct repo (yii2-grid).. this is the yii2-widgets repo

Share more details of what is your code and settings with screenshots (currently cannot make out clearly what you are saying).

**Comment by AleksandrIvin** [comment]
try **'autoclose' => true**
```php
'filter' => DatePicker::widget([
    'model' => $searchModel,
    'attribute' => 'dateOfDrink',                        
    'pluginOptions' => [
    'format' => 'dd-mm-yyyy',
    'autoclose' => true
    ],
```
