### ISSUE TITLE
Datepicker not working with model

### ISSUE THREAD

**Issue by dbd5** [kartik-v/yii2-widgets#241]
<?php

Hello,

I am trying to use Datepicker with my model in a task application, somehow neither the calendar is  opening up not the clearfield button work. I believe I have followed all instructions faithfully - the extension has been installed via composer as part of this widgets bundle. The relevant section of my code is reproduced below, please what am I doing wrong?

Thank You!
____________________________
 
use yii\helpers\Html;
use kartik\widgets\ActiveForm;
use kartik\widgets\DatePicker;
...

<div class="col-lg-4">

	<?= $form->field($model, 'due_date')->widget(DatePicker::classname(), [
		'options' => [
			'placeholder' => 'Enter due date ...',
			],
		'pluginOptions' => [
			'autoclose'=>true
			]
		]);
	?>

</div>
...

**Comment by kartik-v** [comment]
Debug your page for any javascript errors thrown on the console (use Firebug on Firefox for example OR inspect element on Chrome to check errors in the Console).

**Comment by dbd5** [comment]
There was a couple.

All sorted now, Datepicker now working, 

Thanks Bro!
