### ISSUE TITLE
(Select2 + multiple + ajax) populate when update a model

### ISSUE THREAD

**Issue by wilsonfalai** [kartik-v/yii2-widgets#242]
How i populate all attributes when i'm updating a model?

Model A(negociação) hasMany attributes Model B(imoveis).

My Code:
$form->field($model, 'imoveis', ['template' => "{label}{input}"])->widget(Select2::classname(), [

                    'pluginOptions' => [
                            'multiple' => true,
                            'allowClear'         => true,
                            'minimumInputLength' => 1,
                            'ajax'               => [
                                    'url'      => $urlImovelList,
                                    'dataType' => 'json',
                                    'data'     => new JsExpression('function(term,page) { return {search:term}; }'),
                                    'results'  => new JsExpression('function(data,page) { return {results:data.results}; }'),
                            ],
                            'initSelection'      => new JsExpression($initScriptImovel)
                    ],
                    'options' => [
                            //'prompt'   => \Yii::t('app', 'Selecione'),
                            //'multiple' => true,

                    ],

             ]);

**Comment by wilsonfalai** [comment]
if i have $model->imoveis = ['3','4'];
Erro: Array to string conversion
if i have $model->imoveis = '3,4';
Problem: ONLY 1 item show(set) on select2

**Comment by ageusz** [comment]
Have you solved this problem maybe? I'm also struggling with it.

**Comment by kartik-v** [comment]
You may want to just set `options['multiple']` to `true`.

The value for multiple select will be an array. You may need to debug your code and test your controller actions and model code. Ensure your array keys and values are correct and you are not making any mistakes there. Try it with a simple HTML dropdownlist and then do the same with Select2 widget. 

You may [post and request for general programming help and tips in this new Q & A forum](http://webtips.krajee.com/questions).
