### ISSUE TITLE
Active Field widget: kv-fieldset-inline gaps too big

### ISSUE THREAD

**Issue by Erik-r** [kartik-v/yii2-widgets#243]
The CSS option kv-fieldset-inline doesn't work properly anymore since you have introduced a div between "form-group" div container and the input element. This div has the class "col-xx-12" (fullspan).

The consequence is that this div produce grap of 15px each. You can see this on your own demo. (see my attachment).

![field-inline demo](https://cloud.githubusercontent.com/assets/2463365/7113858/43ec048a-e1d8-11e4-92cd-12486e4aeae4.JPG)

I don't know why do you need this fullspan container?

**Comment by kartik-v** [comment]
Check with the updated code - for fixing this.

You may want to check the various enhancement requests and commits in yii2-builder and yii2-widget-activeform on why these changes are needed?

**Comment by kartik-v** [comment]
@Erik-r - you do not need the `kv-fieldset-inline` class anymore... styling is inbuilt within the horizontal form layout.
