### ISSUE TITLE
timepicker is not working

### ISSUE THREAD

**Issue by ajkosh** [kartik-v/yii2-widgets#245]
when i m using this code it is not showing ,
i m using this
<?php echo $form->field($model, 'start_time')->widget(TimePicker::classname(), []);?>
below is attachment how it is showing 
![screenshot from 2015-04-16 20 46 03](https://cloud.githubusercontent.com/assets/8582472/7184455/fbe28876-e47a-11e4-8259-4b84d6ce5b75.png)

**Comment by Wautvda** [comment]
I currently have the same problem. If I use that code snippet I the following error in the javascript console: 
create:181 Uncaught TypeError: jQuery(...).timepicker is not a function(anonymous function) @ create:181m.Callbacks.j @ jquery.min.js:2m.Callbacks.k.fireWith @ jquery.min.js:2m.extend.ready @ jquery.min.js:2J @ jquery.min.js:2

**Comment by kartik-v** [comment]
Cannot reproduce your issue. It seems some problem with application specific other third party CSS or plugins conflicting and breaking your page styles - which you need to debug for your application.

You may [post and request for general programming help and tips in this new Q & A forum](http://webtips.krajee.com/questions).
