### ISSUE TITLE
Can't set predefined Select2 value using Ajax and ActiveForm

### ISSUE THREAD

**Issue by pivorra** [kartik-v/yii2-widgets#246]
Hi,

I really don't understand how using ajax and set predifined values from a previous request.
I want for example initialize select2 value with two french areas like 'auvergne' and 'lorraine'.

I saw an example setting one value as follow, but I never got predefined value display form.
$jsPresetScript = 'function(element,callback){ var initdata=\'{id:"auvergne",text:"auvergne"}\'; callback(initdata);};';

I don't know how to use it with default callback function, and also the format with many values.

Can you please help me?

Regards

My code is like this.

public function getAutocompleteScript($view, $autocompleteUrl) {
    $script = 'function (element, callback) {var id=$(element).val();if (id !== "") {$.ajax("{'.$autocompleteUrl.'}?id=" + id, {dataType: "json"}).done(function(data) { callback(data.results);});}}';
    $view->registerJs($script, $view::POS_END );
    return new JsExpression($script);
}

public function doForm($view) {
    $autocompleteUrl = \yii\helpers\Url::to(['sector-list']);
    $autocompleteScript = $this->getAutocompleteScript($view, $autocompleteUrl);

    $jsPresetScript = 'js:function(element,callback){ var data={id:"lorraine",text:"lorraine"}; callback(data);};';
    $form = ActiveForm::begin(['id' => 'property-form', 'type'=>ActiveForm::TYPE_VERTICAL, 'action' => ['/recherche-immobiliere'], 'method' => 'get']);
    echo $form->field($this, 'geo')->widget(Select2::classname(), [
        'language' => 'fr',
        'size'=>Select2::SMALL,
        'options' => ['placeholder' => 'Région, département, cp, ville ...'],
        'pluginOptions' => [
        'allowClear' => true,
        'multiple' => true,
        'minimumInputLength' => 2,
        'ajax' => [
            'url' => $autocompleteUrl,
            'dataType' => 'json',
            'data' => new JsExpression('function(term,page) { return {search:term}; }'),
            'results' => new JsExpression('function(data,page) { return {results:data.results}; }'),
        ],
        // 'initSelection' => $jsPresetScript,
        'initSelection' => $autocompleteScript,
        ],
    ])->label('Localisation');
    echo FormGrid::widget([
        'model'=> $this,
        'form'=>$form,
        'columns'=>2,
        'autoGenerateColumns'=>false, // override columns setting
        'columnSize'=>Form::SIZE_SMALL,
        'rows'=>$this->getFormRows(),
    ]);
    ActiveForm::end();
}

**Comment by kartik-v** [comment]
You may [post and request for general programming help and tips in this new Q & A forum](http://webtips.krajee.com/questions).

Closing this (please use this repo to report only bugs or enhancements for the related extensions)
