### ISSUE TITLE
Adding new attribute inside option select2 

### ISSUE THREAD

**Issue by moko25** [kartik-v/yii2-widgets#247]
i have script :
```php
echo $form->field($model, 'data')->widget(Select2::classname(), [
    'data' => [array_merge(["" => ""], $data)],
    'options' => [
        'placeholder' => 'Select Data Name', 
        'multiple' => false,
    ],
]);
```
and the result in html :
```html
<select id="storymapdata-data" class="form-control kv-hide input-md" name="Storymapdata[data]">
<optgroup label="0">
<option value="1">Option 1</option>
<option value="2">Option 2</option>
</optgroup>
</select>
```
and my question, how to add attribute 'data-type' inside option?, i want to like this :

&lt;option value=&quot;1&quot; data-type=&quot;wms&quot;&gt;Option 1&lt;/option&gt;
&lt;option value=&quot;2&quot; data-type=&quot;geojson&quot;&gt;Option 2&lt;/option&gt;

**Comment by kartik-v** [comment]
Its the `options` within `options`. Check the [second example in advanced usage section of Select2](http://demos.krajee.com/widget-details/select2#usage-advanced). In the example, the `disabled` property is passed for certain options - you can similarly pass the data attributes.

You may [post and request for general programming help and tips in this new Q & A forum](http://webtips.krajee.com/questions).

**Comment by buttflattery** [comment]
the example you pointed at needs to be appended to a value we know we want to `disable`

```
[
3=>['disabled'=>true]
]
```

how about if  I have the phone number list coming from the database and i want to attach a fontawesome icon just like this [JsFiddle](http://jsfiddle.net/SiamKreative/qCn6p/), how will i specify `Select2` to append let's say `data-icon` attribute to each option in the list. 

My select2 code is below 


```
<?=
$form->field($model, 'phone_id', [
    'template' => '{input}{error}',
])->widget(Select2::className(), [
    'data' => ArrayHelper::map(Yii::$app->user->identity->phoneNumbers,'id','phone_number'),
    'options' => [
        'class' => 'form-control',
        'id' => 'phone_id',
    ],
    'theme' => Select2::THEME_BOOTSTRAP,
    'pluginOptions' => [
        'allowClear' => false,
    ],
])->label(false);
?>
```

**Comment by harabagiuandrei** [comment]
I know this issue is closed long time ago, but i'm looking for something and searching the web didn't yield any positive results. As the example posted here, i'm trying to set some data attribute to the selector options. The only difference that i'm trying to do that using ajax load. Setting the options array inside the options array probably does work only with static data instantiation of the widget (meaning i tried setting it with ajax loading and it won't work). I browsed through your usage examples but couldn't see any useful result.

**Comment by RamiRayya** [comment]
how you did it with ajax load ?? @harabagiuandrei

**Comment by Eli-leo** [comment]
Would you please show us how to do it with ajax loading?  @harabagiuandrei @kartik-v

**Comment by thadudexx** [comment]
json response should look like that
```
[
	{id: 'id1', name: 'Name 1', options: {data-type: 'wms'}},
	{id: 'id2', name: 'Name 2', options: {data-type: 'geojson'}},
	{id: 'id3', name: 'Name 3', options: {data-type: 'something'}},
]
```
on any select2 events like select2:select you can access your data attribute
```
'pluginEvents' => [
	'select2:select' =>'function(event) { console.log(event.params.data.element.dataset.dataType);}',
]
```

**Comment by eggnukes** [comment]
`options` within `options` are not working as expected with `dir` attribute. When setting `dir='rtl'` the label in dropdown is still displayed left to right.
