### ISSUE TITLE
Getting errors on including ActiveForm namespace in form

### ISSUE THREAD

**Issue by mhashimmaqbool** [kartik-v/yii2-widgets#248]
I installed this widget through composer as mentioned in its detail. But when I include ActiveFrom namespace in my form it shows me bunch of errors:

In my _form.php file, I included it in this way:
use kartik\form\ActiveForm;

I also tried including it by:
use kartik\widgets\ActiveForm;

but it was showing error:  ActiveForm not found.

Using this namespace "kartik\form\ActiveForm" it shows following errors:

 PHP User Error – yii\base\ErrorException
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: app\models\Question::getAttributeHint()'

in C:\xampp\htdocs\yii2test\test1\vendor\yiisoft\yii2\base\Component.php:282

Stack trace:
#0 C:\xampp\htdocs\yii2test\test1\vendor\kartik-v\yii2-widget-activeform\ActiveField.php(691): yii\base\Component->__call('getAttributeHin...', Array)
#1 C:\xampp\htdocs\yii2test\test1\vendor\kartik-v\yii2-widget-activeform\ActiveField.php(691): app\models\Question->getAttributeHint('question')
#2 C:\xampp\htdocs\yii2test\test1\vendor\yiisoft\yii2\widgets\ActiveField.php(156): kartik\form\ActiveField->render()
#3 C:\xampp\htdocs\yii2test\test1\views\question\_form.php(28): yii\widgets\ActiveField->__toString()
#4 C:\xampp\htdocs\yii2test\test1\vendor\yiisoft\yii2\base\View.php(325): require('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\yii2test\test1\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile('C:\\xampp\\htdocs...', Array)
#6 C:\xampp\htdocs\yii2test\test1\vendor\yiisoft\yii2\base\View.php(149): yii\base\View->renderFile('C:\\xampp\\htdocs...', Array, NULL)
#7 C:\xampp\htdocs\yii2test\test1\views\question\create.php(23): yii\base\View->render('_form', Array)
#8 C:\xampp\htdocs\yii2test\test1\vendor\yiisoft\yii2\base\View.php(325): require('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\yii2test\test1\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile('C:\\xampp\\htdocs...', Array)
#10 C:\xampp\htdocs\yii2test\test1\vendor\yiisoft\yii2\base\View.php(149): yii\base\View->renderFile('C:\\xampp\\htdocs...', Array, Object(app\controllers\QuestionController))
#11 C:\xampp\htdocs\yii2test\test1\vendor\yiisoft\yii2\base\Controller.php(367): yii\base\View->render('create', Array, Object(app\controllers\QuestionController))
#12 C:\xampp\htdocs\yii2test\test1\controllers\QuestionController.php(297): yii\base\Controller->render('create', Array)
#13 [internal function]: app\controllers\QuestionController->actionCreate()
#14 C:\xampp\htdocs\yii2test\test1\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#15 C:\xampp\htdocs\yii2test\test1\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\yii2test\test1\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('create', Array)
#17 C:\xampp\htdocs\yii2test\test1\vendor\yiisoft\yii2\web\Application.php(83): yii\base\Module->runAction('question/create', Array)
#18 C:\xampp\htdocs\yii2test\test1\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#19 C:\xampp\htdocs\yii2test\test1\web\index.php(12): yii\base\Application->run()
#20 {main}

**Comment by kartik-v** [comment]
Try to update via composer again and get the latest release.

**Comment by mhashimmaqbool** [comment]
Yes.. I only updated the ActiveForm widget via composer and it started working now..

Thanks.
