### ISSUE TITLE
TypeAhead pluginOptions 'minLength' => 0 not working

### ISSUE THREAD

**Issue by Herjanz** [kartik-v/yii2-widgets#249]
The 'minLength' attribute for 'pluginOptions' does not work when set to 0.
According to the official documentation:

name | type | default | description
--------|-------|-----------|---------------
minLength | number | 1 | The minimum character length needed before triggering autocomplete suggestions. You can set it to 0 so suggestion are shown even when there is no text when lookup function is called.

My code:
```php
    <?= $form->field($model, 'organisationId')->widget(Typeahead::classname(), [
	    'dataset' => [
	    	[
	    		'local' => $organisationMap,
	    	]
	    ],
	    'pluginOptions' => ['highlight' => true, 'minLength' => 0],
	    'options' => ['placeholder' => Yii::t('app', 'Search for organisation...')],
	]) ?>
```

**Comment by kartik-v** [comment]
Have you checked with the latest release of the extension and ensured you have the right JS loaded?

**Comment by Herjanz** [comment]
At that time, I did. But after that I found Select2.., which I have been using since. But since this was 8 months ago, this could have been solved by now..
