### ISSUE TITLE
Force dateformat

### ISSUE THREAD

**Issue by thejahweh** [kartik-v/yii2-widgets#250]
Is it possible to force the format which is configured in `i18n`?

If the widget gets the value from a model, it is not possible to override the value which would be a workaround:
```php
$form->field($model, 'from')->widget(DatePicker::className(), [
	'value' => '06.05.2015'
])
```

**Comment by kartik-v** [comment]
You may need to use the [DateControl extension](http://demos.krajee.com/datecontrol) which has been built for this purpose
