### ISSUE TITLE
Need help in adding tags in select 2 from any other input on page

### ISSUE THREAD

**Issue by saifabbasi** [kartik-v/yii2-widgets#251]
Hello!
@Kartik V Thanks for the great widget!

I am using yiur widget with multiple option, it creates tags as i continue select from drop down, how ever i have a grid on page with a button from which i want to add grid's record id and text to be added as a tag in your widget as a tag, let me know any possiblity, i am trying like this, with no luck.
//grid's action column button
'attribute' => 'Action',
'format' => 'raw',
'value' => function ($model) {
return Html::button('Add', [ 'class' => 'btn btn-primary', 'onclick' => 'addSelectedChoice({"id":"'.$model->id.'","text":"'.$model->word.'"})' ]);

i know this function is called inside container, how can i call this function from my button, for now i get a not defined error.

thanks

**Comment by kartik-v** [comment]
I am in the process of upgrading the widget to use the latest Select2 plugin release v4.0. You can try achieve such use cases in that. It has many BC breaking changes. Will update soon. Closing this as of now. Refer #252.
