### ISSUE TITLE
echo redirecting me to another page

### ISSUE THREAD

**Issue by kalai131192** [kartik-v/yii2-widgets#254]
pendingController.php

public function actionPending()
    {   
       
        $today = date('Y-m-d');
                    
        $dt1 = ArrayHelper::map(Claimprocess2::find()->all(),'id','turn_around_time_set');
        $dt2 = ArrayHelper::map(Claimprocess2::find()->all(),'id','updated_at');
        $name = ArrayHelper::map(Claimprocess2::find()->all(),'id','id');
        foreach ($dt1 as $key => $value) 
        {
            $trt = print_r($value, true);
            $update = print_r($dt2[$key], true);
            $name1 = print_r($name[$key], true);

            if($today == $trt)
            {
                $sql = "INSERT INTO pending (claimer_name, status, template, last_trt, email) 
                        SELECT claimprocess_start_for, status, template, turn_around_time_set, tpa_email  
                        FROM claimprocess_2 WHERE id = $name1 ";

                $query = Yii::$app->db->createCommand($sql)->execute();

                echo '<div class="alert alert-success"> Pendings Availble </div>';
                
            }
            else
            {
                echo '<div class="alert alert-success"> No Pendings Availble </div>';
            }

            
        }
        
    }

index.php

<?= Html::a('Check Pendings', ['pending/pending'], ['class' => 'btn btn-primary', 'id' => 'pendings']) ?>

Here am executing this code using button in my index file, but the problem is when i press the button   
, echo navigating me to another, but i dont need that, i need to do in same page.

if i replace echo with return, function is not working, help me to sort out this problem, thank you

**Comment by kartik-v** [comment]
Not related to the extension.

You may [post and request for general programming help and tips in this new Q & A forum](http://webtips.krajee.com/questions).
