### ISSUE TITLE
error is not hiding when i remove file from upload

### ISSUE THREAD

**Issue by ajkosh** [kartik-v/yii2-widgets#255]
i m uploading file ,if file type is not ok then it is giving me error ,that is fine but if i removed file from attachment then error should not display ,below is attachment
![screenshot from 2015-05-18 15 20 05](https://cloud.githubusercontent.com/assets/8582472/7678569/d885e4de-fd72-11e4-8210-ecc5e31353a5.png)

**Comment by kartik-v** [comment]
You need to reset your form by creating a reset form button to clear the error.
