### ISSUE TITLE
Select2

### ISSUE THREAD

**Issue by dudunegrinhu** [kartik-v/yii2-widgets#257]
I cannot add a placeholder if I'm in the form grid builder

**Comment by derekisbusy** [comment]
Post you config. You may need to move the placeholder to pluginOptions if you're using the new release.

**Comment by kartik-v** [comment]
You may [post and request for general programming help and tips in this new Q & A forum](http://webtips.krajee.com/questions).

Closing this (please use this repo to report only bugs or enhancements for the related extensions).
