### ISSUE TITLE
DepDrop problem with new jquery version(2.1.4)

### ISSUE THREAD

**Issue by wilsonfalai** [kartik-v/yii2-widgets#258]
In console i got the following error: Uncaught TypeError: Cannot use 'in' operator to search for 'length' in 

When I use the jquery version 2.1.3 this problem does not happen

**Comment by kartik-v** [comment]
Get updated release. This is resolved via kartik-v/dependent-dropdown#22. Also there are a few enhancements for Select2 as in kartik-v/yii2-widget-depdrop#15.
