### ISSUE TITLE
When assigning a attribute, value is not working anymore

### ISSUE THREAD

**Issue by jelmertjuh** [kartik-v/yii2-widgets#259]
<?= Select2::widget([
                'name' => 'competence_ids',
                'model' => $model,
                'value' => ArrayHelper::getColumn($model->competence, 'cid'),
                'data' => ArrayHelper::map(Competence::find()->all(), 'cid', 'compcode'),
                'pluginOptions' => [
                    'tags' => true,
                    'multiple' => true,
                ],
            ]); ?>`

results in:
![works](https://cloud.githubusercontent.com/assets/2157311/7750116/b2e46428-ffd2-11e4-9de1-879fd195972f.png)

    <?= Select2::widget([
                'name' => 'competence_ids',
                'model' => $model,
                'attribute' => 'competence_ids',
                'value' => ArrayHelper::getColumn($model->competence, 'cid'),
                'data' => ArrayHelper::map(Competence::find()->all(), 'cid', 'compcode'),
                'pluginOptions' => [
                    'tags' => true,
                    'multiple' => true,
                ],
            ]); ?>

results in:
![notworking](https://cloud.githubusercontent.com/assets/2157311/7750146/d7ef72b2-ffd2-11e4-99a4-7900f84ba603.png)

Am I doing something wrong?

**Comment by nunomaduro** [comment]
Why did you need to assign a attribute ?

**Comment by jelmertjuh** [comment]
First I tried this, that doesn't work either:

    <?= $form->field($model, 'competence_ids')->widget(Select2::classname(), [
                'name' => 'competence_ids',
                'value' => ArrayHelper::getColumn($model->competence, 'cid'),
                'data' => ArrayHelper::map(Boks::find()->all(), 'cid', 'compcode'),
                'pluginOptions' => [
                    'tags' => true,
                    'multiple' => true,
                ],
            ]); ?>

When I assign `model' and 'attribute' to Select2::widget([]), I do the same as when I do $form->field($model, 'competence_ids'); right?
I though that do it the Select2::widget([]) way may solved the problem but unfortunately no luck.

**Comment by kartik-v** [comment]
You need to do some reading and understanding of yii active form and model handling using yii input widgets. You do not pass for input widgets the `name` and `value` properties when using with `model` as they will not be recognized. They will be used only when using without `model`. Its same when using with active form.

For Select2 widget do check the [basic usage examples](http://demos.krajee.com/widget-details/select2#usage-basic) for usage with active form, usage without active form etc.

**Comment by jelmertjuh** [comment]
I understand that, but in the tagging support area on your usage page, there is only an example without ActiveForm.
The widgets works correct when I have:

    <?= $form->field($model, 'competence_ids')->widget(Select2::classname(), [
            'name' => 'competence_ids',
            'value' => ArrayHelper::getColumn($model->competence, 'cid'),
            'data' => ArrayHelper::map(Boks::find()->all(), 'cid', 'compcode'),
            'pluginOptions' => [
                'tags' => true,
                'multiple' => true,
            ],
        ]); ?>

But the tags that are already selected ($model->competence) does not appear when assigning value.
