### ISSUE TITLE
TimePicker vs GridView

### ISSUE THREAD

**Issue by andrewblake1** [kartik-v/yii2-widgets#260]
Timepicker doesn't appear to play well as a GridView filter. 1 problem is it seems to cause an endless loop due to triggering change event which bubbles to gridview which reloads and then the timepickers change event triggers again and so on. A shame - would have been good in a FieldRange as as filter.

Probably just close this. I don't think it will be possible to have these 2 widgets work together - will use time part of date time picker instead in Gridview and remove the months bit.

Apologies, raised this before I really thought about it.

**Comment by kartik-v** [comment]
Duplicate to kartik-v/yii2-grid#21 and kartik-v/yii2-grid#241
