### ISSUE TITLE
datepicker is not working with dynamically crated element.

### ISSUE THREAD

**Issue by devmca** [kartik-v/yii2-widgets#261]
Hi Kartik, I am using kartik-v/yii2-widget-datepicker. It is working perfect with normal elements.
But when i am using it with dynamic element, it is not working.

My code is like this
<?php echo DatePicker::widget([
	'model' => $model,
	'attribute' => '['.$index.']start_date',
	'options' => ['placeholder' => 'Start date','class' => 'form-control','required'=>'required'],
	'pluginOptions' => [
	         'autoclose'=>true
	]
]);?>

**Comment by kartik-v** [comment]
You need to write your own JS code to intiialized date picker plugin if you are not rendering it on document ready.
