### ISSUE TITLE
Select2 + kartik\GridView recieving 'Array to string conversion' error

### ISSUE THREAD

**Issue by Ralef** [kartik-v/yii2-widgets#262]
When I'm using Select2 as a filter to GridView I'm recieving 'Array to string conversion'
```php
[
        'class' => '\kartik\grid\DataColumn',
        'filterType' => \kartik\grid\GridView::FILTER_SELECT2,
        'filterWidgetOptions' => [
            'data' => \app\models\Status::getMappedStatuses($projectId, $phaseId),
            'options' => [
                'multiple' => true
            ],
        ],
        'attribute' => 'status',
        'value' => function (Oprs $model) use ($projectId, $phaseId) {
            return $model->getStatusAsString($projectId, $phaseId);
        }
],
```
Where `\app\models\Status::getMappedStatuses($projectId, $phaseId)` returns mapped array `$id => $value`

**Comment by kartik-v** [comment]
You do not seem to be using it correct. This seems to be a problem in your dataprovider code that will parse this filter query.

You are having a string value for your field...but your filter select2 is setup as a multiple select which will return an array and also read values as an array.  

Your query for the grid dataprovider on the other hand is reading this filter attribute as a string... and not parsing this as an array - unless you override the default dataprovider query generated by gii.
