### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by olessavluk** [kartik-v/yii2-widgets#263]
Hi! 
After last `composer update` I realize that yours DepDrop plugin not working. And there is no errors in console, no request to server, just not working. I tried to rollback DepDrop back to `v1.0.0` it doesn't help, but rollback all your composer dep. to older working versions helped. So I've hardcoded all versions in main `composer.json` file.

I think that placing `*` in composer.json for all packages is a bad design idea (same bad as making widget packs like this one, better to install those you really need) - https://getcomposer.org/doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md
Because sometimes(most of the time) I don't need fresh updates, I just need something to work.

**Comment by olessavluk** [comment]
seems that problem was with `dependent-dropdown v1.4.2`, because with `v1.4.0` seems to be working

**Comment by kartik-v** [comment]
NOTE THAT AL EXTENSIONS are being clearly versioned now (its done for most - but some are pending)... you need to actually have a correctly configured `composer.json` for your app to correctly install what you need. If you do not care about versions set `dev-master` and `minimum-stability` to `dev`. But its assumed that only stable version extensions will be installed.
Latest release of [dependent-dropdown](https://github.com/kartik-v/dependent-dropdown) v1.4.2 is not yet tagged.

Also note that `yii2-widgets` was created much before. It was split later into sub-packages...  and this package just exists for backward compatibility. You can install its extensions individually .

Note that versioning of specific dependencies are already set/done for most extensions -- it will be done for the pending extensions.

**Comment by kartik-v** [comment]
Refer [related discussion](https://github.com/kartik-v/yii2-widget-select2/issues/50#issuecomment-115744957).

**Comment by olessavluk** [comment]
Ok, thank's for your reply. 
I'll try to find where is incompatibility problem between those versions of dependent-dropdown and provide this information to you
