### ISSUE TITLE
Not working for tags in grid filter

### ISSUE THREAD

**Issue by dudunegrinhu** [kartik-v/yii2-widgets#264]
Select2 is not working for tags in grid. When I add as a filter and click on the filter it just keep loading.

This is my code

[
    		'attribute'=>'user_id',
    		'value' => 'DriverName',
    		'header' => 'Driver',
		 'hAlign' => GridView::ALIGN_CENTER,
    		'vAlign' => GridView::ALIGN_MIDDLE,
    		'filterType'=>GridView::FILTER_SELECT2,
    		'filter'=>ArrayHelper::map(Driver::find()->asArray()->all(), 'driver_id', 'display_name'),
    		'filterWidgetOptions'=>[
    			'pluginOptions'=>[
    				'tags'=>true,
    				'multiple'=>true,
    			],
    		],
    		'filterInputOptions'=>['placeholder'=>'Select a Driver...', 'multiple'=>true],
    	],

**Comment by dudunegrinhu** [comment]
Hi Any answer on this?

**Comment by kartik-v** [comment]
You may need to check your code for entire search model and dataprovider generation that filters the grid (if you are using tags property the value returned will be an array just like a multi select dropdown and not a string -  so you need to check your filter functions accordingly).

You may [post and request for general programming help and tips in this new Q & A forum](http://webtips.krajee.com/questions).
