### ISSUE TITLE
initialPreview on FileInput

### ISSUE THREAD

**Issue by JamesBarnsley** [kartik-v/yii2-widgets#265]
Is it possible to use the PDF viewer in the initialPreview option for the FileInput.

When I upload a file using the FileInput the PDF viewer works fine, but when it comes to viewing the file on an update form using the initialPreview I cannot use the PDF viewer? Is there a way to do it?

**Comment by kartik-v** [comment]
Beyond scope of this extension. You need to use an embed component (or iframe) .. that supports PDF view of files from servers OR use certain browser plugins that help you achieve this.

You may [post and request for general programming help and tips in this new Q & A forum](http://webtips.krajee.com/questions).
