### ISSUE TITLE
fileinput cant display

### ISSUE THREAD

**Issue by joshuadiezmo** [kartik-v/yii2-widgets#267]
why my fileinput cannot display? its forever loading.
![screen shot 2015-08-06 at 5 40 12 pm](https://cloud.githubusercontent.com/assets/8644115/9108682/62c3a63a-3c62-11e5-91e4-c598eac9d1bb.png)

**Comment by kartik-v** [comment]
Avoid raising duplicate issues. Duplicate to kartik-v/yii2-widget-fileinput#38.

[See related comment](https://github.com/kartik-v/yii2-widget-fileinput/issues/38#issuecomment-128316392).
