### ISSUE TITLE
Inconsistency between datepicker and timepicker

### ISSUE THREAD

**Issue by JamesBarnsley** [kartik-v/yii2-widgets#269]
Hi,

I have noticed an inconsistency between the datepicker and timepicker.

With the datepicker I can click the input field or the icon button and the datepicker opens.

With the timepicker I can only click the input icon and the timepicker opens but not the input field.

James.

**Comment by kartik-v** [comment]
It is based on the source jQuery plugin support and all have different plugin authors who have their own functionality. You may want to report enhancements to the individual plugin author.
