### ISSUE TITLE
Compatibility with johnitvn/yii2-ajaxcrud

### ISSUE THREAD

**Issue by zmoddynamics** [kartik-v/yii2-widgets#270]
Hi, I love the yii2-ajaxcrud extension above but it appears none of your widgets are compatible with it? Any thoughts? I've rendered your widgets before with renderAjax from an ajax call and its worked fine so I'm not sure really why your widgets are compatible with the above extension... Any thoughts?

**Comment by kartik-v** [comment]
I have unfortunately not gone through the above extension - so cannot comment. You may try reaching  out to the author.

**Comment by zmoddynamics** [comment]
Hi, thanks for the response.

I have contacted the author but I don't understand his feedback. Here is the thread link:

https://github.com/johnitvn/yii2-ajaxcrud/issues/23

It seems as though his plugin requires that all  assets be registered from the page making the Ajax call; but in your widgets the assets are registered automatically from within their individual views.

At least, that is what I understood from the above link.

Sent from my iPhone

On Aug 17, 2015, at 12:35 AM, Kartik Visweswaran <notifications@github.com<mailto:notifications@github.com>> wrote:


I have unfortunately not gone through the above extension - so cannot comment. You may try reaching out to the author.

-

**Comment by kartik-v** [comment]
Yes using `renderAjax` to render the widget should help in most cases wherever there is a content to be rendered on an ajax based response. However, I am not sure how to do that in the extension you mention?


In addition to renderAjax helping you, the widgets from offer a couple of `data-krajee` HTML5 data attributes within the native HTML input markups in most cases as well for you to access and refresh the plugin options via javascript.
