### ISSUE TITLE
Select2 with ActiveForm have search issue when renderAjax

### ISSUE THREAD

**Issue by sanjarbek** [kartik-v/yii2-widgets#272]
Hi, I show my form on modal. Contents getted via renderAjax. Select2 widget used with activeform. Everything is working except search property of select2.

**Comment by kartik-v** [comment]
You may need to debug your code and check for JS errors / messages on your browser console.

You may [post and request for general programming help and tips in this new Q & A forum](http://webtips.krajee.com/questions).
