### ISSUE TITLE
DateControl submiting with wrong date

### ISSUE THREAD

**Issue by danfsd** [kartik-v/yii2-widgets#275]
I have previously used the DateTimePicker with success, but now that I'm using it on a new project, i'm stumbling on a strange behavior:

The model's date is, no matter what I fill in on the widget, December 31th 1899.

This is what is being submitted on the form:

```php
Array
(
    [_csrf] => azFoeW0uNUEjYhI1LxldFh5QKxZbalAmP2EeJgBWXiU4aSVBPlp3Mw==
    [Event] => Array
        (
            [name] => Kartik Event
            [start_date] => 1899-12-31 06:55:34
            [holiday] => 0
        )

    [start_date-event-start_date] => Oct 17, 2015, 7:55:34 pm
)
```

This is how the field is being configured:
``` php
    <?= $form->field($model, 'start_date', [
        'template' => '{label}*<div class="row"><div class="col-md-4">{input}{error}{hint}</div></div>'
    ])->widget(DateControl::classname(), [
        'type' => DateControl::FORMAT_DATETIME,
        'ajaxConversion' => false,
        'options' => [
            'pluginOptions' => ['autoclose' => true]
        ]
    ]) ?>
```

Note that this is the very same code that I used on the previous project that I mentioned before.
I know that this must be a silly error, but still I haven't found it yet. Can I have some light here?

Thanks in advance!

**Comment by kartik-v** [comment]
It just means your FORMATS read by the widget is not correct. You need to check your SAVE format exactly matches the data and the DISPLAY format also exactly matches the data.

**Comment by danfsd** [comment]
Hmm, that was exactly the problem. But still, I solved it by enabling the ajaxConversion. Thanks for the support and the amazing work that you do!

Cheers!
