### ISSUE TITLE
Load default values from model

### ISSUE THREAD

**Issue by albertborsos** [kartik-v/yii2-widgets#276]
I tried to use tags input with a model on update scenario. If I try it without model it is ok, but with model it is not. Am I missed something? Thanks!

```php
<div class="form-group field-usercms-rules">
    <label class="control-label" for="usercms-rules">Rules</label>
    <?= \kartik\select2\Select2::widget([
        'name' => Html::getInputId($model, 'rules'),
        'value' => $model->getRules(\app\models\UserCms::DATA_TYPE_SELECTED),
        'data' => $model->getRules(\app\models\UserCms::DATA_TYPE_SOURCE),
        'pluginOptions' => [
            'tags' => true,
            'multiple' => true,
            'width' => '100%',
            'tokenSeparators' => [',', '\n'],
        ],
    ]) ?>
    <div class="help-block"></div>
</div>

<?= $form->field($model, 'rules')->widget(\kartik\select2\Select2::className(), [
    'data' => $model->getRules(\app\models\UserCms::DATA_TYPE_SOURCE),
    'pluginOptions' => [
        'tags' => true,
        'multiple' => true,
        'width' => '100%',
        'tokenSeparators' => [',', '\n'],
    ],
]) ?>
``` 
![kepernyofoto 2015-10-14 - 10 52 06](https://cloud.githubusercontent.com/assets/7307145/10479088/30d742d6-7262-11e5-95d7-40a541e99185.png)

**Comment by SelenIT** [comment]
@albertborsos, have you found the solution? I also had the similar problem with multiple default selections from the model (#277). Your first example helped me, thanks, but having the general solution still would be nice.

**Comment by albertborsos** [comment]
Yes. If you just use `$model->load(Yii::$app->request->post())` in the controller, you will overwrite the default values with an empty array. So you will need to wrap this like:

```php
if (Yii::$app-request->isPost) {
    if ($model->load()) {
        ...
    }
}
```
