### ISSUE TITLE
Select2: is it possible to select multiple values by default?

### ISSUE THREAD

**Issue by SelenIT** [kartik-v/yii2-widgets#277]
I use a multi-value Select2 instance (as a ListBox replacement) for a model with `hasMany` relation. So the model I need to pass to the widget is an array (returned by the ActiveRecord's `all()` method). If I pass only one element of this array, it is correctly converted to the Select2 option selected by default, but in case of an array it seems to be completely ignored (nothing is selected).

I need to make several options selected by default, corresponding to all `hasMany` relations of my model. Is it possible?

**Comment by albertborsos** [comment]
maybe you need to map the results of `all()` like `ArrayHelper::map($results, 'key_column_name', 'text_column_name')` and pass this for the default values.

**Comment by kartik-v** [comment]
It should be similar to how you would do it for a Yii default `listBox` - an array of values from your relational model.
