### ISSUE TITLE
 how to get gridview based on my input in dropdown 

### ISSUE THREAD

**Issue by zameer-s** [kartik-v/yii2-widgets#279]
hi, im very new to yii2, im stuck at some point of project, it would be very helpful if i get some help from here.

i want to fetch data from database im using karthik gridview to display, my question is  when i use drop down and select the dropdown filter , only that particular filter should happen along with it should have select all dropdown option.
for example:
i have dropdown say  countries,states,district. and if i select particular country and state and district iam able to search on that, but im unable to make select all.
i want select all in this way.
example:
iam selecting dropdown say country (vaue india) and state (value karnatka) and i select district as select all
i need to display values based on india,karnataka and  all districts

thanks in advance

**Comment by kartik-v** [comment]
You may [post and request for general programming help and tips in this new Q & A forum](http://webtips.krajee.com/questions).
