### ISSUE TITLE
Typeahead on show value is wrong

### ISSUE THREAD

**Issue by tsdogs** [kartik-v/yii2-widgets#280]
When I use a Typeahead associated with a model, on edit the value is not displayed (but is assigned to the title of the span)
if I change the value, this is displayed, if I reselect the same value it won't be displayed.

**Comment by kartik-v** [comment]
Cannot understand the issue. Seems this is not related to a bug or enhancement for this extension.

You may [post and request for general programming help and tips in this new Q & A forum](http://webtips.krajee.com/questions).

**Comment by tsdogs** [comment]
Of course it's related. Maybe it's my setup (though I doubt it as it's pretty standard). I'll try to give more detail with an example (some code and screenshots) within some time.
