### ISSUE TITLE
Select2 tag ajax and ActiveForm - tags not loading from field

### ISSUE THREAD

**Issue by ageusz** [kartik-v/yii2-widgets#281]
Select2 widget is not able to load data from model`s `tags` attribute. Here is the view code:
```php
<?=
    $form->field($model, 'tags')->widget(Select2::classname(), [
        'options' => [
            'placeholder' => 'Tagi',
            'multiple' => true,
        ],
        'pluginOptions' => [
            'tags' => true,
            'allowClear' => true,
            'minimumInputLength' => 3,
            'ajax' => [
                'url' => $url,
                'dataType' => 'json',
                'data' => new JsExpression('function(params) { return {q:params.term}; }')
            ],
            'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
            'templateResult' => new JsExpression('function(tag) { return tag.name; }'),
            'templateSelection' => new JsExpression('function (tag) { return tag.name; }'),
        ],
    ])
    ?>
```

When creating new model it's working fine but I can't work out or find the answer - how the `tags` property should look like so the widget initialize properly? An array of key-value pairs? It's not working. 

That's big problem (bug?) because it makes it impossible to use on ActiveForm as docs suggests.

**Comment by kartik-v** [comment]
Not sure what is the problem. An [example for multiple tags initialization with preselected values has been mentioned in the docs & demos](http://demos.krajee.com/widget-details/select2#usage-tags).

The example includes Select2 usage without ActiveForm.

For an active form with model, the initial value will be read directly via the model attribute. So in your code above:
```
$model->tags = ['red', 'blue'];
$form->field($model, 'tags')->widget(Select2::classname(), [ 
    // options
]);
```
should display you the pre-selected tags.

**Comment by ageusz** [comment]
It has been mentioned but not with ajax enabled. Actually when I remove line:
```
'templateSelection' => new JsExpression('function (tag) { return tag.name; }'),
```
it displays fine but autocomplete is not working anymore.

**Comment by kartik-v** [comment]
You can refer this with the plugin author (since this is a plugin specific configuration)... or the plugin docs and check how you could achieve your use case. Am keeping this issue open.
