### ISSUE TITLE
Feature request for ActiveForm: Hints as questions mark or label hover and popup

### ISSUE THREAD

**Issue by Enrica-r** [kartik-v/yii2-widgets#283]
Per standard hints are written under the input control. This allows short hints only and it's not very stylish because the form is streched even there are no hints.

The forms of Gii have a short javascript included which hides the hint block, adds a help class to label and activates bootstrap's popover. If you move the mouse over a label the hint is shown in the bootstrap popover.

Another possibility instead of underlying the label there could be a question mark icon after the label or the control.

Could you add an option to ActiveForm which adds this popovers like in Gii?

I propose a parameter with following options:
- standard (default): as is currently
- dotted label with hover over label
- question mark after label with hover over question mark and label
- question mark after control with hover over question mark

Here is Gii's JS code how they did it:
```php
    var initHintBlocks = function () {
        $('.hint-block').each(function () {
            var $hint = $(this);
            $hint.parent().find('label').addClass('help').popover({
                html: true,
                trigger: 'hover',
                placement: 'right',
                content: $hint.html()
            });
        });
    };
```
Result:
![activeform_hint_popup](https://cloud.githubusercontent.com/assets/2463365/11296711/17223948-8f74-11e5-8e83-f40e08c62c4e.JPG)

**Comment by kartik-v** [comment]
Refer enhancement request in kartik-v/yii2-widget-activeform#64.
