### ISSUE TITLE
How a can use templateSelection only isNewRecord?

### ISSUE THREAD

**Issue by wilsonfalai** [kartik-v/yii2-widgets#285]
I have the below code:
'initValueText' =>\common\models\Produto::findOne($modelAcaoProduto->produto_id)->codigo;,
'templateSelection' => new JsExpression('function(params) { return params.codigo;}')

When I am entering a new record everything works perfectly, but when I'm editing the registry the field is empty. Should show your value entered in initValueText

How could I use 'templateSelection' only a new record? 
*because when I'm not using templateSelection on NotNewRegister(editing), the select2 work normally and shows the value in the field

**Comment by kartik-v** [comment]
You can configure your widget differently based on `$model->isNewRecord` 
```php
if ($yourmodel->isNewRecord) {
   $pluginOptions['templateSelection'] = new JsExpression('function(params) { return params.codigo;}')
}
// then use $pluginOptions to configure your widget
```

**Comment by kartik-v** [comment]
You may [post and request for general programming help and tips in this new Q & A forum](http://webtips.krajee.com/questions) in future.
