### ISSUE TITLE
ColorInput script registration is broken

### ISSUE THREAD

**Issue by Nekroido** [kartik-v/yii2-widgets#287]
The generated javascript is:
```
jQuery.when(jQuery("#").spectrum(spectrum_6ad2fc5c)).done(function(){jQuery("#").spectrum('set',jQuery("#eventform-color").val());jQuery("#eventform-color-cont").removeClass('kv-center-loading');});
```

As you can see there is no input element's id. To fix this I had to change:
```
$input = 'jQuery("#' . $this->html5Options['id'] . '")';
```
to:
```
$input = 'jQuery("#' . $this->options['id'] . '")';
```
in **registerColorInput()** method of **ColorInput.php**.

Another way to fix this is to explicitly specify element's id in 'html5Options' like this:
```
<?= $form->field($event, 'color')->widget(ColorInput::className(), [
            'html5Options' => [
                'id' => 'eventform-color',
            ],
            'options' => [
                'id' => 'eventform-color',
                'placeholder' => 'Select color ...'
            ],
        ]) ?>
```
Yet the input has default looks of Spectrum widget.

**Comment by kartik-v** [comment]
The first configuration is LOGICALLY NOT CORRECT and will cause erronaeous behavior. It must be `html5Options['id']` and not `options['id']`. T

You may not have updated the packages correctly - you need to ensure you have the latest release of `yii2-krajee-base` and `yii2-widget-colorinput`. You may [cross check this with the demos](http://demos.krajee.com/widget-details/colorinput#basic-usage).

The `html5Options['id']` should be automatically generated if you have not provided it. It seems you have an outdated version of `yii2-krajee-base` and / or you have not updated packages via composer or there is some dependency issue on your app which is resulting in outdated package version being installed.

**Comment by Nekroido** [comment]
Yes, I had version 1.7.8 of yii2-krajee-base installed. That's odd, because I have been using your awesome library since yesterday (installed via Composer and still have command prompt opened). Anyway, I had it updated and everything's working fine now. Thank you so much!
