### ISSUE TITLE
StarRating - icon issue

### ISSUE THREAD

**Issue by igor-chepurnoi** [kartik-v/yii2-widgets#288]
Hi, i use StarRating in my project and icons on separate device are not displayed. When i open my site on mobile, all the icons look as question marks. How can i resolve it? maybe needs some font library?

My code:
```php
echo StarRating::widget([
                    'id' => "id",
                    'name' => "name",
                    'value' => 5,
                    'disabled' => true,
                    'pluginOptions' => [
                        'step' => 1,
                        'symbol' => html_entity_decode('&#x235f;', ENT_COMPAT, "utf-8"),
                        'showClear' => false,
                        'showCaption' => false,
                        'size' => 'sm',
                    ]
              ]);
```

**Comment by kartik-v** [comment]
The plugin by default relies on bootstrap glyphicons and bootstrap CSS to be loaded. You may need to check if your device browser is capable of reading and  rendering the css3 styles.

**Comment by igor-chepurnoi** [comment]
Okay, thanks.
