### ISSUE TITLE
StarRating - required

### ISSUE THREAD

**Issue by alexburpeeblu** [kartik-v/yii2-widgets#289]
Previously the application that I am working on allowed for the straight up skipping of star ratings provided with this application. Now, we want to make sure that that section is required. Everything I've seen around says that it needs to be done with stuff like Yii's built in validation - which is fine. I figured that meant that all I needed to do was set that field to required under the rules and I did so.

Going to the form and trying to submit it shows me that this works.. great!

![2fb0f528-9ff3-11e5-95e9-ba8ee6891ee4](https://cloud.githubusercontent.com/assets/15630822/12119532/a71138e0-b3a2-11e5-82d7-17f40da21007.png)

So let's just click on one and then pass the form in..

![3b026074-9ff3-11e5-81c8-1343c8290ee6](https://cloud.githubusercontent.com/assets/15630822/12119531/a70cb90a-b3a2-11e5-84fd-e65fc20982aa.png)

Any insights as to why this isn't working?

**Comment by kartik-v** [comment]
You may want to try this with the latest extension releases and let know. It does not seem to be reproducible in the newer releases. Will reopen if you find otherwise and share.
