### ISSUE TITLE
undefined option index

### ISSUE THREAD

**Issue by ajkosh** [kartik-v/yii2-widgets#292]
![screenshot from 2016-01-23 14 10 46](https://cloud.githubusercontent.com/assets/8582472/12529429/63778eee-c1db-11e5-8300-e59dc78a5df8.png)
![screenshot from 2016-01-23 14 11 01](https://cloud.githubusercontent.com/assets/8582472/12529430/63d975dc-c1db-11e5-8c25-62d703f6419b.png)

**Comment by kartik-v** [comment]
This seems to be a yii2-grid query. This is not an issue any more with yii2-grid extension - you can get the latest releases.
