### ISSUE TITLE
How to disable depdrop

### ISSUE THREAD

**Issue by Francogo** [kartik-v/yii2-widgets#293]
Hi,
  My issue is a question.
  I'm looking for a way to disabled(ie grey) the select2 depdrop in some condition. When "disabled" the dropdown should show the current value and drop down should be disabled.
  I did try to add the 'disabled'=>true in many places without success.
François

**Comment by kartik-v** [comment]
Render a normal dropdownList or HTML Select with disabled false, instead of using DepDrop widget for your use case.

**Comment by moysoft** [comment]
It's useful to have a disabled state for the DepDrop component. For example if the state is closed then all of the form fields automatically disabled, it's funny if the user can alter the field that's already closed.
