### ISSUE TITLE
clear selection via jquery

### ISSUE THREAD

**Issue by kankerlijer** [kartik-v/yii2-widgets#294]
How can i clear a selected value programmatically via jquery?

i tried something like this?
`$(this).find(".select2-selection__clear").click();`

but this doesn't seem to do it? any suggestions?

**Comment by kankerlijer** [comment]
fixed;
`$(this).select2().val("").trigger("change");  `

**Comment by yogi9096** [comment]
This is worked for me-

$('#accessories').val('').trigger("change");
//#accessories   is the id of select2
