### ISSUE TITLE
Select2 Widget + maintainOrder=>true + multiple => true not maintain order when update

### ISSUE THREAD

**Issue by wilsonfalai** [kartik-v/yii2-widgets#295]
On documentations says:
echo Select2::widget([
    'name' => 'color_2',
    'value' => ['red', 'green'], // initial value
    'data' => $data,
    'maintainOrder' => true,
    'options' => ['placeholder' => 'Select a color ...', 'multiple' => true],
    'pluginOptions' => [
        'tags' => true,
        'maximumInputLength' => 10
    ],
]);
But if i set  the opposite ['green','red',] on select2 view show firt red and after green(ordered by name). Not maintain order

**Comment by kartik-v** [comment]
Check if you have the updated coderelease and update to the latest dev-master release. This works fine on the dev-master release.
