### ISSUE TITLE
New Color input is not working in dynamic form.

### ISSUE THREAD

**Issue by by12** [kartik-v/yii2-widgets#298]
HI, 
   First off all thanks for your great contribution. I am using the danymic form
" https://github.com/wbraganca/yii2-dynamicform " to save color attribute value by using kartik color input widget. " https://github.com/kartik-v/yii2-widget-colorinput ". 
problem is when i add new input filed color select not loaded only loading circle show there.  
my code is:
 <?= $form->field($modelItem, "[{$i}]string_title")->widget(ColorInput::classname(), [
options' => ['placeholder' => 'Select color ...'],
   ]);  ?>

out put is:
![color](https://cloud.githubusercontent.com/assets/16643776/14421307/27da4f96-ffd1-11e5-874c-3302ec606a8b.png)

thanks in advance.

**Comment by PriyaD08** [comment]
Even I am facing this issue. Kindly update.

**Comment by by12** [comment]
Hi, 
   sorry for late reply.  I think the problem is not with the dynamic form. Actual dynamic form not able to handle the colorinput master branch. they are not compatible to each other. I just used the color input 1.0.0 version and solve the problem for me. with new version of ColorInput widget you need to update the dynamic form script.
