### ISSUE TITLE
SwitchInput alignment on Horizontal ActiveForm

### ISSUE THREAD

**Issue by gael-wogenstahl** [kartik-v/yii2-widgets#305]
Hello Kartik,

I tried to put a `SwitchInput` widget in an `ActiveForm` using `kartik\widgets\ActiveForm` and it seems the layout is broken with that combination.

Here is my code :
```php
<?php $form = ActiveForm::begin(['type' => ActiveForm::TYPE_HORIZONTAL, 'formConfig' => ['deviceSize' => ActiveForm::SIZE_SMALL]]); ?>
    <?= $form->field($user, 'utl_email') ?>
    <?= $form->field($user, 'utl_prenom') ?>
    <?= $form->field($user, 'utl_nom') ?>
    <?= $form->field($user, 'customerAdmin')->widget(SwitchInput::classname()) ?>
    ...
<?php ActiveForm::end(); ?>
```
And here is the layout rendered :
![image](https://cloud.githubusercontent.com/assets/5624541/15597147/4b2901ce-2419-11e6-826f-1ffb381148fa.png)

It seems there is a left padding of 12 pixels involved on `input` that is not reproduced with the `form-group` you use to encapsulate the `bootstrap-switch`.

This time I wasn't able to solve the issue myself so I'm calling for your help.
Thank you in advance for taking a look !

**Comment by gfericsanjr** [comment]
`<?= $form->field($user, 'customerAdmin')->widget(SwitchInput::classname(), ['containerOptions' => []]) ?>`

**Comment by gael-wogenstahl** [comment]
Awesome ! Thank you !
Maybe that should be in the documentation ?
