### ISSUE TITLE
ActiveForm - add edit forConfig functionality

### ISSUE THREAD

**Issue by aadutskevich** [kartik-v/yii2-widgets#309]
If you have a big form with many diffrent models you need to change form layout or lableSpan. But there is no functionality to set this values. It will be very helpfull if you add some kind of setters for formConfig fields or just common function to edit formConfig. E.g.:

> /**
     * @param array $formConfig
     */
    public function editConfig($formConfig){
        $this->formConfig = array_replace_recursive($this->formConfig, $formConfig);
    }

**Comment by kartik-v** [comment]
This will be more so addressed via kartik-v/yii2-widget-activeform#76.
