### ISSUE TITLE
select2 is hidden on modal form that is loaded via ajax

### ISSUE THREAD

**Issue by narshon** [kartik-v/yii2-widgets#310]
Hi Kirtik,

I'm using the select2 widget from this namespace: kartik\widgets\Select2. However, in a modal form it doesn't appear. I checked the generated html and I see its code is there but with a display:none style and these classes: kv-plugin-loading loading-select2_XXXX. where XXXX is my field name.

Kindly help.

**Comment by malcolmyam** [comment]
having the same issue as narshon. the <select> is generated but it's hidden somehow

**Comment by powertech2nd** [comment]
Im having the same problem, 
It appear when I initailize the select.

In my case, the select2 get generated (with append) by a button click, and at the button click action i put the initialize code. After i initialiaze it, the problem occurs.

**Comment by kartik-v** [comment]
Read about the [related issue and solution here](https://github.com/kartik-v/yii2-widget-select2/issues/41#issuecomment-339957858).
