### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by ncramer** [kartik-v/yii2-widgets#315]
I'm working through implementing BS4 Alpha / yii-bootstrap.

I'm using your ActiveForm extension and experiencing surprisingly good results.

However, there are some minor changes required from what I've seen so far.

Are you planning to support Bootstrap 4?

If so, would you be interested in a running list of nits based on my experience?

**Comment by kartik-v** [comment]
Currently only supporting BS3 as BS4 as you mentioned is still in alpha.

Still I can open up a BS4 branch and you can submit a PR/enh request there.

**Comment by Mi5i** [comment]
We are planning to use BS4 beta in our project. Are you still not planning to support Bootstrap 4?

**Comment by kartik-v** [comment]
The BS4 support is to a large extent dependent on Yii2 core support for the same, including jquery 3.x support (currently yii supports only jquery 2.x), and `yii2-bootstrap` extension to fully support BS4 in a stable release.

Till the above pre-requisite is achieved, it will be really difficult.

However all of [Krajee built jQuery plugins](http://plugins.krajee.com) now include support for both Bootstrap 4 and Bootstrap 3.
