### ISSUE TITLE
update with DepDrop Widget

### ISSUE THREAD

**Issue by NatalyMac** [kartik-v/yii2-widgets#316]
Hi:) thank you for that awesome widget:) 
I have some question  about using it when I want to update records from database.
I use that widget for adding records with nested selections as example 1 or 2 and 
I want to use the same form to update. I want to show the data from the database in the input fields, and have possibility to select other option like in example 3.
But when I set  'data' with some data I lose possibility to select anything else, just is not any data.
 I check your example scenario 3. You use for that just single table, my data is in different linked tables .
Help me to figure out, how it possible to do. Thank you very much.

**Comment by kartik-v** [comment]
You need to write your own queries to fetch linked records from other tables. If unclear, you can check the yii guide on how to queries and writing and linking to tables.
