### ISSUE TITLE
I don't understand how to implement this

### ISSUE THREAD

**Issue by drusixtynine** [kartik-v/yii2-widgets#317]
Sorry, but I am a beginner, so these questions could seem so basic

In the example DepDrop Basic Usage you are giving , I don't get some thing to implement this 
I need to make 2 dependent dropdowns, I did put this code in my _form

    <?= $form->field($model, 'idCulture')->dropDownList(ArrayHelper::map(culture::find()->where(['idSociete'=>Yii::$app->session->get('idSociete')])->all(), 'id','nomCulture'),['prompt'=>'Sélectionnez une Culture']); ?>

    <?= $form->field($model, 'idVariete')->widget(DepDrop::classname(), ['options'=>['id'=>'nomVariete'],'pluginOptions'=>['depends'=>['idCulture'],'placeholder'=>'Select...','url'=>Url::to(['/site/subcat'])]]); ?>

I don't know what to put in Url ? I am running this on a yii2 basic app

Also The controller code must be something like that, but I don't know in which controller to put it?
And I don't know  how to do the getSubCatList function and where to put it too???

    public function actionNomVariete() {
    $out = [];
    if (isset($_POST['depdrop_parents'])) {
        $parents = $_POST['depdrop_parents'];
        if ($parents != null) {
            $nomCulture = $parents[0];
            $out = self::getSubCatList($nomCulture); 
            // the getSubCatList function will query the database based on the
            // cat_id and return an array like below:
            // [
            //    ['id'=>'<sub-cat-id-1>', 'name'=>'<sub-cat-name1>'],
            //    ['id'=>'<sub-cat_id_2>', 'name'=>'<sub-cat-name2>']
            // ]
            echo Json::encode(['output'=>$out, 'selected'=>'']);
            return;
        }
    }
    echo Json::encode(['output'=>'', 'selected'=>'']);
}

if you can help me in some way, that would be really nice 👍

**Comment by drusixtynine** [comment]
nobody to help?
maybe a working demo I can download, then I'd manage...

**Comment by ydakilux** [comment]
Take a look there :
 
http://stackoverflow.com/questions/23951520/dependent-dropdown-yii2-how-to-do

  Kinds Regards

**Comment by drusixtynine** [comment]
I will, thanks

**Comment by drusixtynine** [comment]
hey ydakilux,
did you get it to work
Cause I still don't manage...

**Comment by ydakilux** [comment]
I didn't tested it, but when you follow krajee's website it mostly ok
  Did you follow the post, or the explanation from krajee's website ?
  Did you write the view, and the controller ? Wich part is not working.
  Are you getting an ajax response from the server when you test it (ajax array). You can test it manually.
  what are you getting on screen or not ?

**Comment by drusixtynine** [comment]
Thanks again for following this with me. I actually am not managing to properly test 

I have a product page with Culture (Id, nomCulture) and Variete (id, idCulture, nomVariete), Variete is dependent on Culture, so in the product page form, I have 2 dropdowns as follows with depDrop extension :

     <?= $form->field($model, 'idCulture')->dropDownList(ArrayHelper::map(culture::find()->where(['idSociete'=>Yii::$app->session->get('idSociete')])->all(), 'id','nomCulture'),['prompt'=>'Sélectionnez une Culture']); ?>

    <?= $form->field($model, 'idVariete')->widget(DepDrop::classname(), ['options'=>['id'=>'nomVariete'],'pluginOptions'=>['depends'=>['idCulture'],'placeholder'=>'Sélectionnez une Variété','url'=>Url::to(['/nomVariete'])]]); ?>

First question, what shall I put for the url of the second dropdown? is it a path to Variete? the model? the controller?

Also, for the controller code, here is what I think I should add, but it doesn't look that I should anything here. My question though is 'in what file shall I put this function? My Product controller? My Culture controller? my Variete controller? or a new blank file with only this function? Shall the URL point to this file?':

public function actionNomVariete() {
$out = [];
if (isset($_POST['depdrop_parents'])) {
$parents = $_POST['depdrop_parents'];
if ($parents != null) {
$cat_id = $parents[0];
$out = self::getSubCatList($cat_id);
echo Json::encode(['output'=>$out, 'selected'=>'']);
return;
}
}
echo Json::encode(['output'=>'', 'selected'=>'']);
}

What I have on screen for the moment is the Culture dropdown which works normally, but the Variete dropdown is always greyed...

**Comment by drusixtynine** [comment]
hey Ydakilux? am I asking too much?

**Comment by kartik-v** [comment]
Could you please post help and programming guidance at the [webtips forum](http://webtips.krajee.com) and/or the yii forum. Use this repo for reporting only extension related issues.
