### ISSUE TITLE
yii2 using kartik select2 in a sweet alert not working

### ISSUE THREAD

**Issue by yokoshima1** [kartik-v/yii2-widgets#329]
hello
my problem is explained in http://stackoverflow.com/questions/41174194/yii2-using-kartik-select2-in-a-sweet-alert-not-working 
and i haven't got an answer yet.
thnx

**Comment by kartik-v** [comment]
Am not sure of the sweet alert setup.. but it seems it is a javascript/jquery based component where you are trying to embed select2... in that case you need to check and write your client code/JS accordingly - so that select2 is instantiated after your sweet alert is rendered
