### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by elvenpath** [kartik-v/yii2-widgets#351]

**Comment by elvenpath** [comment]
I see a lot of issues, most of them without any replies. No commits in the past 2 years also. So, i cannot help but wonder if is this still active.

**Comment by kartik-v** [comment]
This repo is a collection of widgets which have their own separate repo... Most issues are discussed or resolved there. Unfortunately not got time to sift through issues here... Will do so when I get time.

**Comment by lamplinx** [comment]
yes
