### ISSUE TITLE
Feature Request - Translation Support

### ISSUE THREAD

**Issue by sparkyway** [kartik-v/yii2-widgets#358]
I18N translation support for this messages, to be able to customize the English version of the message:

![image](https://user-images.githubusercontent.com/37216916/37419436-008e43f0-27a4-11e8-950f-9c2cb386a140.png)

**Comment by kartik-v** [comment]
Its supported in the bootstrap-fileinput plugin. Read the [plugin docs for options supported](http://plugins.krajee.com/file-input/plugin-options). You can set the [`pluginOptions['language']`](http://plugins.krajee.com/file-input/plugin-options#language) property to get the translated message for your language. Alternatively you can customize the message via [`pluginOptions['dropZoneTitle']`](http://plugins.krajee.com/file-input/plugin-options#dropZoneClickTitle).
