### ISSUE TITLE
Excel error

### ISSUE THREAD

**Issue by Danielesk** [kartik-v/yii2-widgets#369]
When I export the data with kartik\grid\GridView, the following is displayed when opening Excel....
![excel_error](https://user-images.githubusercontent.com/10652829/45669474-cca6dc80-bb52-11e8-89d8-55c3624f7d0f.png)

I have a problem when I upload it with this file.
Only files with these extensions are allowed: xls.

Why is this, please tell me the solution.

**Comment by kartik-v** [comment]
Gridview excel exports are actually HTML format saved as XLS. 

Newer releases of excel does not open them by default. You need to allow this on your client by unblocking the file.  Refer [related topic](https://social.technet.microsoft.com/Forums/en-US/4a15e472-a265-4058-b439-7d79c2670817/xls-file-will-not-open-in-excel-2016-only-gray-view?forum=excel)
