### ISSUE TITLE
Kartik-v/yii2-widget is DatePicker is not working with the renderPartial().

### ISSUE THREAD

**Issue by dubeymahi48** [kartik-v/yii2-widgets#73]
When i use DatePicker in my form this is not working  and after the refresh of page it is good, I think this is due to ajax loading so help me what is an error is being done by me??????

**Comment by harryalwanga** [comment]
Hi the above solution has not assisted me any other solution?

**Comment by suthra** [comment]
replace 
return $this->renderPartial('viewfilename');
with
return $this->renderAjax('viewfilename');
