### ISSUE TITLE
DepDrop json

### ISSUE THREAD

**Issue by TsarS** [kartik-v/yii2-widgets#77]
I use DepDrop and i have this error in Chrome console -
"Uncaught TypeError: Cannot use 'in' operator to search for '8' in Cape Town " by jQuery. But array in console - 
244: "Cape Town"
245: "Pretoria"

**Comment by johnsunam** [comment]
in my controller
    public function progs($id)
    {
return ArrayHelper::map(FacultyRecord::find()->where(['university_id'=>$id])
    ->select(['id','name'])->asArray()->all(),'id','name');
    }
    public function actionProgram()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $id = $parents[0];
                $out = self::progs($id);
                            echo Json::encode(['output'=>$out, 'selected'=>'']);
                return;
            }
        }
        echo Json::encode(['output'=>'', 'selected'=>'']);
    }
in my view
<?= $form->field($model,'university')->dropDownList($university,['id'=>'university']);?>
 <?= $form->field($model, 'faculty')->widget(DepDrop::classname(), [
    'options'=>['id'=>'name'],
    'pluginOptions'=>[
    'depends'=>['university'],
    'placeholder'=>'Select...',
    'url'=>\yii\helpers\Url::to(['contents/program'])
    ]
    ])?>
when i run this code i am getting this erron on my browser console and in my child dropdown on loading is shown 
Uncaught TypeError: Cannot use 'in' operator to search for 'length' in HUMANITY
here HUMANITY is my list for select option in parents dropdown

**Comment by johnsunam** [comment]
please me to sort it out

**Comment by whmemon** [comment]
I am getting 

TypeError: id is undefined on line no. 40 in file dependent-dropdown.js

can not get whats the problem
