### ISSUE TITLE
Selected option in Select2

### ISSUE THREAD

**Issue by it3rmit** [kartik-v/yii2-widgets#87]
Hi.
Is there an opportunity to specify the selected option for the select2 widget? It is very useful for editing field, that already have some value.

**Comment by KrunalHingu** [comment]
hello there.
 i'm facing the problem to get selected options from database while using select 2 ,
select 2 is fetching only single option but when i store multiple option its not working properly. will you please guide me.?
Thanks.
![screenshot_1](https://cloud.githubusercontent.com/assets/11865749/7061139/2d6c64b4-deab-11e4-9518-3fcbca63bb6b.png)

**Comment by pivorra** [comment]
Hi,

I really don't understand how using ajax and set predifined values from a previous request.
I want for example initialize select2 value with two french areas like 'auvergne' and 'lorraine'.

I saw an example setting one value as follow, but I never got predefined value display form.
$jsPresetScript = 'function(element,callback){ var initdata=\'{id:"auvergne",text:"auvergne"}\'; callback(initdata);};';

I don't know how to use it with default callback function, and also the format with many values.

I there somebody helping me on this topic.


My code is like this.

	public function getAutocompleteScript($view, $autocompleteUrl) {
		$script = 'function (element, callback) {var id=$(element).val();if (id !== "") {$.ajax("{'.$autocompleteUrl.'}?id=" + id, {dataType: "json"}).done(function(data) { callback(data.results);});}}';
		$view->registerJs($script, $view::POS_END );
		return new JsExpression($script);
	}
	
	public function doForm($view) {
		$autocompleteUrl = \yii\helpers\Url::to(['sector-list']);
		$autocompleteScript = $this->getAutocompleteScript($view, $autocompleteUrl);
		
		$jsPresetScript = 'js:function(element,callback){ var data={id:"test",text:"test"}; callback(data);};';
		$form = ActiveForm::begin(['id' => 'property-form', 'type'=>ActiveForm::TYPE_VERTICAL, 'action' => ['/recherche-immobiliere'], 'method' => 'get']);
		echo $form->field($this, 'geo')->widget(Select2::classname(), [
			'language' => 'fr',
			'size'=>Select2::SMALL,
			'options' => ['placeholder' => 'Région, département, cp, ville ...'],
			'pluginOptions' => [
			'allowClear' => true,
			'multiple' => true,
			'minimumInputLength' => 2,
			'ajax' => [
				'url' => $autocompleteUrl,
				'dataType' => 'json',
				'data' => new JsExpression('function(term,page) { return {search:term}; }'),
				'results' => new JsExpression('function(data,page) { return {results:data.results}; }'),
			],
			// 'initSelection' => $jsPresetScript,
			'initSelection' => $autocompleteScript,
			],
		])->label('Localisation');
		echo FormGrid::widget([
			'model'=> $this,
			'form'=>$form,
			'columns'=>2,
			'autoGenerateColumns'=>false, // override columns setting
			'columnSize'=>Form::SIZE_SMALL,
			'rows'=>$this->getFormRows(),
		]);
		ActiveForm::end();
	}

Regards

**Comment by asimnzm** [comment]
hi selected option in select2 for ajax not working in edit form it shows blank
following is my code
echo $form->field($model, 'customer_id')->widget(Select2::classname(), [
    		'options' => ['placeholder' => 'Search for a Customer ...'],
    		
    		'pluginOptions' => [
    				'allowClear' => true,
    				'minimumInputLength' => 2,
    				'ajax' => [
    						'url' => $url,
    						'dataType' => 'json',
    						'data' => new JsExpression('function(term,page) { return {search:term}; }'),
    						'results' => new JsExpression('function(data,page) { return {results:data.results}; }'),
    				],
    				'initSelection' => new JsExpression($initScript)
    		],
    ]);

**Comment by asimnzm** [comment]
solved i just initialized the value in view
$initScript = <<< SCRIPT
function (element, callback) {
    var search=\$(element).val();
   
    if (search !== "") {
        \$.ajax("{$url1}?search=" + search, {
            dataType: "json"
        }).done(function(data) { 
        		
        		callback(data.results[0]);
});
    }
}
SCRIPT;

**Comment by hafeesbharathi** [comment]
if($id!=null):
$request->event_id=$id;
endif;
?>

<?
                echo $form->field($request, 'event_id')->widget(Select2::classname(), [
                  'data' =>$events,
                  'language' => '',
                  'options' => ['multiple' => false, 'placeholder' => 'Select Event'],
                  'pluginOptions' => [
                  'allowClear' => true
                  ],
                ])->label('Select Event'); 
            ?>

**Comment by Schreeedi** [comment]
@jatin7591: this worked for me

```php
<?php
$selection = explode(",", $string_from_database);
$js = "";
foreach ($selection as $val) {
	$js .= "$('#w0 option[value=". $val ."]').attr('selected','selected').change();";
}
$this->registerJs($js, yii\web\View::POS_READY);
?>
```

In this case $string_from_database must be the values from the options comma-separated in one string.

**Comment by msaprykin** [comment]
Hello,
this is a problem, in Grid select have as empty value
``` 
'status' => [
    'value'=>function($model) {
        return $model->getStatustext();
    },
    'class' => \mcms\xeditable\XEditableColumn::className(),
    'url' => 'editable',
    'dataType'=>'select',
    'editable'=>[
        'placement' => 'right',
        'source'=> ['Publicated', 'Deleted'],
    ],
    'attribute' => 'status',
    'format' => 'raw',
],
```

**Comment by liamgcarter** [comment]
Hiya.

I am having an issue setting the selected value within the Select 2 widget
I am using it within the form widget and without a model

`'province_id'=>['type'=>Form::INPUT_WIDGET,	'widgetClass'=>'\kartik\widgets\Select2', 'options'=>[
    //'value'=>$_GET['search-form-sales']['province_id'],										
   'data'=> ArrayHelper::map(Province::find()->orderBy('text')->asArray()->all(), 'id','text'),
   'value'=>50, 
   'options' => [
      'placeholder' => 'Province',
   ],
   'pluginOptions' => [
      'allowClear' => true
   ],
],],`

As you can see I have tried the $_GET property and now I have made the value static. The id 50 isn't set as selected, I have tried removing the placeholder and it then just displays the first option.

Any ideas

Regards

Liam

**Comment by hendrasyp** [comment]
Hi, thanks for this awesome widget. But I still can't selected default value. it happening when I try to update data: 
```
// if model are newRecord
$data = ArrayHelper::map(ContactGroups::find()->where(['group_status'=>'ACTIVE'])->asArray()->all(),'group_id', 'group_name'); 

if (!$model->isNewRecord)
{
  $data = ArrayHelper::map(ContactGroups::find()->joinWith('contactContactGroups')->where(['group_status'=>'ACTIVE','contact_contact_groups.contact_id'=>$model->contact_id])->asArray()->all(),'group_id', 'group_name'); 
}

echo $form->field($model, 'group_id')->widget(Select2::classname(), [
                 'data' => $data,
                  'language' => 'en',
                  'options' => ['placeholder' => Yii::t('modules','Pilih Kelompok')],
                  'pluginOptions' => [
                    'tags'=>true,
                    'allowClear' => true,
                    'multiple' => true,
                  ],
              ])->label('Kelompok');
```

**Comment by nasmy** [comment]
Hi Guys. I have Solved this issue. Please try

<?php
if(!$model->isNewRecord){
    $id=$model->id;
    //$speciality=ArrayHelper::map(\app\models\Doctorspeciality::find('doctorId')->all(),'id');
    $rows = (new \yii\db\Query())
        ->select(['specialityId'])
        ->from('Doctorspeciality')
        ->where(['doctorId' => $id])
        ->all();

    $result = ArrayHelper::getColumn($rows, 'specialityId');
}
?>
<?php
    echo '<label class="control-label">Speciality</label>';
    echo Select2::widget([
        'name' => 'speciality',
        'data' => ArrayHelper::map(\app\models\Speciality::find()->all(),'id','specialityName'),
        'value'=>(!$model->isNewRecord ? $result : ''),
        'options' => [
            'placeholder' => 'Select Speciality ...',
            'multiple' => true
        ],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]);
    ?>

**Comment by Matijt** [comment]
Hi, I would like to know how can I do to display the information of the dropbox but being able to write the value. Just like if the dropdown would be examples of what could be in the text field. Like a history of what the user already wrote there, but he can write what he considers best for the occasion.

**Comment by srikanth15794** [comment]
Can anyone please help me to select a default value on page load in select2 filed  used in yii2 dynamic form widget ?

**Comment by Matijt** [comment]
srikanth15794

Something like this:
```
<?php
$model->category = 2;  // value to initialize
echo Select2::widget([
   'model' => $model,
   'attribute' => 'category',
   'data' => $data
]);
?>
```
https://github.com/kartik-v/yii2-widgets/issues/87

You just need to establish a value.

**Comment by iamahmudul** [comment]
Hello, I am looking for something that can be done using CJuiAutoComplete extension but here I want to use Eselect2, because I want a dropdown with a search option. But when selecting a value from dropdown,  I want to populate 4 other fields. Is there any option in select2? By the way I'm using Yii1

**Comment by ghost** [comment]
I had been suffering from using Select2 with a form + model. The issue at the end is very simple. You can not use an attribute in your model that is assigned to a DB field. You just create another attribute, add it to your rules as safe, then use this field:

```
$model->booksetsArray = ArrayHelper::getColumn($model->bookBooksets, 'bookset_id');

    echo $form->field($model, 'booksetsArray')->widget(Select2::classname(), [
    'data' => ArrayHelper::map($booksets, 'id', 'title'),
    'attribute' => 'booksetsArray',
    'language' => 'en',
    'options' => ['placeholder' => '--- Select ---', 'multiple' => true],
    'pluginOptions' => [
        'allowClear' => true,
        'tags' => true
    ],
    ]);
```

I will move setting booksetsArray to afterFind() method in the model, but it does the work.

I hope it helps someone.
