### ISSUE TITLE
yii2-widgets depDrop on update scenario

### ISSUE THREAD

**Issue by dubeymahi48** [kartik-v/yii2-widgets#95]
please help me for depDrop on update scenario::-- 

When we call an updateAction() then second dropdown is blocked until we not select previous dropdown. But if first dropdown is selected then second should be load the previous selected value.

 <?= $form->field($model, 'country_pk')->dropDownList($model->countryList, ['prompt' => '-Choose a Country-', 'id' => 'country_pk']) ?>

```
<?php
echo $form->field($model, 'state_pk')->widget(DepDrop::classname(), [
    'options' => ['id' => 'state_pk'],
    'pluginOptions' => [
        'depends' => ['country_pk'],
        'placeholder' => 'Select State...',
        'url' => Url::to(['subcat'])
    ]
]);
?> 
```

onCreate() everything is OK..please help me how to enable the desable second dropdown if it have value why it bocked..

Thank you...

**Comment by akshaybande81** [comment]
Can you share the code for update .

**Comment by paskuale75** [comment]
@akshaybande81 you could pass the param 'selected' in the url with your model->attribute value

`'url' => Url::to(['subcat','selected' => $model->myAttribute])`
