### ISSUE TITLE
DatetimePicker no inital value and other position

### ISSUE THREAD

**Issue by Enrica-r** [kartik-v/yii2-widgets#96]
I have one page in which I use DatePicker (via DateControl) and DatetimePicker (also via DateControl)
DatetimePicker starts with a date in year 1899 always while Datepicker takes the given value from input. see Screenshots:
![datetimepicker_nok](https://cloud.githubusercontent.com/assets/2463365/3373545/87b94160-fbb4-11e3-91d2-936585a651d1.JPG)
![datepicker_ok](https://cloud.githubusercontent.com/assets/2463365/3373548/90754dc6-fbb4-11e3-861b-e59b986aa06e.JPG)

Further Datepicker checks which is best position top or bottom and it starts left of input field. Datetimepicker goes out of screen without pluginOptions. In screenshot I set `'pluginOptions' => ['pickerPosition' => 'top-left']`. As you can see it's better but it's not at the same place as Datepicker. It's not relevant for functionality but it's not good for application's common behavior.

**Comment by evmiru** [comment]
Hello, how to fix? I use the plugin with the following settings, just use the slider fotorama (fotorama.io) on the page. Calendar opens in the slider.
` 
<div class="fotorama" data-max-width="100%"  data-nav="thumbs" data-allowfullscreen="true" data-ratio="465/692" data-thumbheight="89"  data-thumbwidth="60" data-swipe="true" data-loop="true">
<img>...<img>...
</div>
...
<?php Pjax::begin(); ?> <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    [
                        'filter' => DatePicker::widget([
                            'model' => $searchModel,
                            'attribute' => 'date_from',
                            'attribute2' => 'date_to',
                            'type' => DatePicker::TYPE_RANGE,
                            'separator' => '-',
                            'pluginOptions' => [
                                'format' => 'yyyy-mm-dd',
                                'todayHighlight' => true,
                            ]
                        ]),
                        'attribute' => 'date',
                        'format' => 'datetime',
                    ],
...`
